
A lot can happen in six days. A tired graduate student can write the bulk of his dissertation. A gaming system might reshape an entire landscape. Of these two events, it is likely that the latter is of greater interest, and so I will briefly detail it here. 

In 2010, Microsoft released the Kinect, a gaming peripheral for the Xbox 360 that, unlike other gaming consoles, did not require any controllers to use. Instead, the Kinect used dual infrared emitters/sensors and RGB cameras to create a 3D depth map in real-time @shottonRealTimeHumanPose. Simply put, the person _was_ the controller. Initially, the Kinect was a commercial success, earning the Guinness World Record for "Fastest-Selling Consumer Electronics Device". Over the years however, the Kinect was gradually phased out of us until its official discontinuation in 2017 @pandeSlowPainfulDeath2023. 

One could tell this story from a purely commercial perspective and call the Kinect a failure. That however, is only half the story. 

Today, there is an abundance of software available to track human movement for the curious user, whether researcher, animator, or hobbyist. This was not the case in the pre-deep learning revolution era. Devices that could provide the kind of depth and tracking data the Kinect did typically cost tens of thousands of dollars, well out of hand for the everyday consumer. Then suddenly, that same technology was available for a tidy sum of \$150. Many developers saw the potential in this software, if only it were freed from its proprietary, closed-source chains. The same day the Kinect released, Adafruit, an open-source hardware manufacturer and vendor, posted a \$3000 bounty to be awarded to the first person to open-source the Kinect drivers. An interesting note here is that this contest was actually proposed and funded by a core developer on the Kinect team who had been frustrated with Microsoft's reluctance to offer any PC support @KinectDeveloperClaims.

Within 6 days, the Kinect was hacked, the bounty awarded, and its first open-source driver posted online.

Suddenly, Kinect units were being bought not for gaming, but to create artwork and develop low-cost robotic navigation. Microsoft was reluctant to support such endeavors, but this early work evolved into OpenKinect community. Although Microsoft was initially reluctant to support these uses, the scale of community adoption and market demand ultimately led to the release of official PC support in 2012. It was at this point yet another community saw the benefit of this hardware. The biomechanics research and clinical community suddenly had a method of motion capture available to them not gated behind cost or hard-to-parse academic code. There are numerous studies that detail usage of the Kinect for clinical and research use @ValidityMicrosoftKinect2012 @jebeliStudyValidatingKinectV22017 @yeungEvaluationMicrosoftKinect2014. Even though several limitations @pfisterComparativeAbilitiesMicrosoft2014 (e.g. occlusion causing major issues due to the single camera view point) were identified, the cost and availability of the system made it one of the first available-to-researchers systems.

Today, the Kinect is gone. Though later iterations such as the Azure Kinect extended its lifespan as a developer tool, those too have been discontinued. It is my opinion that release of the Kinect itself did not trigger any fundamental change in the research community. In fact, if Microsoft had its way, the system would never have been used for non-gaming purposes at all. Rather, it was 6 days in which a community came together to make a piece of technology available for all. The Kinect is gone, but its story reveals the impact that low-cost accessible hardware, combined with open-source software, can have on the research landscape. 


