Markerless motion capture could expand quantitative movement measurement beyond specialized laboratories, but researchers need methods that adapt to different questions, environments, and computer-vision tools. We present FreeMoCap, a free, open-source method for reconstructing 3D human movement from synchronized consumer-grade cameras. FreeMoCap pairs low-cost multi-camera recording with a modular architecture that decouples pose estimation from reconstruction and biomechanical analysis, turning pose-estimation models into interchangeable components of a shared measurement framework. We validated a six-camera FreeMoCap system against a marker-based reference during treadmill gait and clinical standing balance. The system produced biomechanically meaningful data from low-cost hardware, with gait joint-center errors generally below 30 mm, sagittal joint-angle errors of 2–5°, and center-of-mass balance metrics that showed excellent agreement with reference data. Critically, the shared framework revealed task, speed, and backend-dependent differences in markerless performance, establishing FreeMoCap as both an accessible measurement method and an extensible framework for evaluating evolving pose-estimation algorithms.


Markerless motion capture is a series of hardware and software methods to reconstruct 3D movement without the need for markers. Current solutions tend to treat each step in this pipeline as a fixed assumption, which imposes limitations on the hardware and research applications. Here, we present FreeMoCap, a free, open-source method for reconstructing 3D human movement using multiple pose-estimation algorithms with synchronization methods from multiple kinds of cameras. We validated a six-camera FreeMoCap system using low-cost webcams (\$20) against a marker-based reference during treadmill gait and clinical standing balance using three different pose estimation backends. Results showed that the system was capable of producing biomechanically meaningful data (saggital joint RMSE < 5° and [something about COM results]) and that system performance was influenced by task and pose estimation backend. These results establish that markerless motion capture is not a one-size-fits-all solution and that an extensible framework can provide a platform for evaluating and improving pose estimation algorithms for movement science applications, while making motion capture more accessible to researchers without access to specialized hardware.

---
Markerless motion capture reconstructs three-dimensional movement from video without physical markers, but current implementations typically lock users into fixed hardware, a single pose estimation model, and rigid processing pipelines — limiting both the research questions that can be asked and who can ask them. Here, we present FreeMoCap, a free, open-source method that provides a complete, modular pipeline from synchronized video acquisition through biomechanical analysis, supporting interchangeable pose estimation backends and consumer-grade cameras. We validated a six-camera FreeMoCap system (~$20 webcams) against a marker-based reference (Qualisys) during treadmill gait and clinical standing balance, comparing three pose estimation backends. Sagittal joint angle errors were below 5°, spatiotemporal gait parameters showed excellent agreement (ICC > 0.90), and center-of-mass balance metrics were sensitive to condition changes — with performance varying across backends and tasks. By providing validated, open-source benchmarking infrastructure on accessible hardware, FreeMoCap lowers the barrier for researchers to collect motion capture data, evaluate pose estimation algorithms, and build a shared evidence base for markerless motion analysis.

---
Markerless motion capture reconstructs three-dimensional movement from video without physical markers, but current implementations typically couple [a specific] pose estimation to fixed hardware and rigid pipelines, limiting both who can capture movement data and how readily advances in computer vision can be translated into research and clinical practice. Here, we present FreeMoCap, a free, open-source ~~method~~ [tool] that provides a complete, modular pipeline from synchronized video acquisition through biomechanical analysis, designed to scale across hardware configurations, pose estimation algorithms, and research applications. We validated a six-camera FreeMoCap system using ~\$20 webcams and three pose estimation backends against a marker-based reference (Qualisys) during treadmill gait and clinical standing balance. Sagittal joint angle errors were below 5°, spatiotemporal gait parameters showed excellent agreement (ICC > 0.90), and center-of-mass balance metrics were sensitive to condition changes in the CTSIB-M balance assessment — with performance varying across backends and tasks. By providing validated, open-source infrastructure that connects advances in pose estimation to biomechanical measurement, FreeMoCap lowers the barrier for researchers to collect and benchmark motion capture data across contexts.

--

Dear Editors,

We wish to inquire whether the following work would be appropriate for Nature Methods.
We have developed a free, open-source markerless motion capture system that provides a full pipeline from video recording through 3D reconstruction and biomechanical analysis, runs on consumer-grade webcams, and supports interchangeable pose estimation backends. Since its release, the software (FreeMoCap)has been adopted by over 12,500 users across approximately 140 countries, used in published research spanning gait biomechanics, clinical balance, reaching kinematics, and computational linguistics, and has an active open-source community (~7,500 GitHub stars, ~3,700 Discord members).

We have completed a validation study comparing FreeMoCap against a marker-based Qualisys system across treadmill gait at five walking speeds and clinical standing balance (CTSIB-M), evaluating three pose estimation backends through the shared pipeline. A key finding is that backend choice interacts with the measurement task in ways that would not be apparent from single-domain validation — which we believe speaks to a broader methodological need in the field for open, multi-context evaluation infrastructure as markerless tools move toward clinical and research adoption.

We see this as a potential fit for Nature Methods because the contribution is primarily methodological and infrastructure-oriented: not just a validation of one system, but a framework that enables the movement science community to systematically evaluate and translate pose estimation algorithms as they continue to emerge from the computer vision field. 
Sincerely,
...