== Discussion

Our findings suggest that when integrated with a prosthesis-specific model, the markerless motion capture system was sufficiently sensitive to changes in gait resulting from controlled alignment adjustments to an above-knee prosthesis during treadmill walking. Across all alignment conditions, the markerless system preserved the ranking and directionality of major biomechanical changes relative to the marker-based reference system. These changes spanned multiple biomechanical domains: leg length adjustments altered pelvic symmetry; ankle dorsiflexion/plantarflexion adjustments altered sagittal plane knee and ankle kinematics and minimum toe clearance; and toe-in/toe-out adjustments altered foot progression angle. In each case, the markerless system was able to maintain condition ordering, preserving meaningful biomechanical signals despite increased stride-to-stride variability; however, absolute accuracy varied by biomechanical metric. 

A notable finding of this work is that pose estimation errors introduced by the prosthetic limb were not confined to the prosthetic segments themselves, but propagated to other body keypoints estimated by RTMPose. This manifested most clearly in gait event timing for the non-prosthetic limb, which exhibited substantially greater stride-to-stride variability than the prosthetic limb tracked by the custom DeepLabCut model (swing duration SD: 132.1 ms vs. 29.6 ms), and in pelvic obliquity estimates, which depend on hip joint center localization from RTMPose. Kinematics tracking with RTMPose has been shown to be accurate in able-bodied populations @ceriolaComparativeAnalysisMarkerless2024, so this error propagation likely reflects RTMPose's reliance on learned spatial relationships between body segments; i.e., the atypical appearance of a prosthetic limb disrupts these priors and degrades estimates of anatomically adjacent keypoints. This finding has practical implications beyond this study--it suggests that hybrid pipelines using a generic model for body tracking alongside a prosthesis-specific model should be designed with awareness of cross-segment error propagation, and that validation should explicitly assess non-prosthetic limb accuracy even when those segments are not the primary focus. 

The biomechanical metrics captured by the markerless system in this study are clinically meaningful. Prior work has indicated that leg length discrepancies as small as 5-10 mm can negatively impact the prosthesis user @fodorCompensationLegLength2025 @gordonLegLengthDiscrepancy2019. Sagittal plane alignment deviations in persons with transfemoral amputation have been shown to elicit compensatory strategies, including increased hip extension moments and reduced step length, to maintain prosthetic knee stability @koehler-mcnicholasBiomechanicalResponsePersons2016.  Foot progression angle deviations are recognized clinically as a common gait deviation requiring alignment correction @hashimotoProperSequenceDynamic2023. Across all three planes, prosthetic malalignment in persons with transfemoral amputation has been linked to asymmetric loading on the intact limb and elevated long-term risk of osteoarthritis @zhangEffectProstheticAlignment2019, underscoring the clinical importance of detecting even subtle alignment deviations. The ability of the markerless system to accurately capture and distinguish changes in these metrics suggests potential use in clinical alignment assessment.

Current clinical practice relies on a range of outcome measures, from patient-reported questionnaires assessing perceived mobility to functional performance tests such as the 6-Minute Walk Test and Timed Up and Go. While these measures are well-suited to the time constraints of a clinical appointment, they fall short of capturing detailed biomechanical data needed to optimize prosthesis alignment. Markerless motion capture has the potential to overcome the cost and equipment barriers that have historically kept instrumented gait analysis out of routine clinical care. In a clinical setting, markerless motion capture could be used to monitor patient progress across appointments, inform prosthetist alignment decisions, and provide objective biomechanical evidence to support payer justification for prosthetic components. Together, these capabilities highlight a longstanding gap between the biomechanical rigor of research settings and the practical realities of everyday clinical care, and as markerless systems continue to develop, high-quality gait analysis may become a routine part of prosthetic clinical practice. 

The results of this study extend prior work on pose estimation for prosthesis users in two important respects. Zhou et al. demonstrated that standard OpenPose models produce substantial joint coordinate errors in lower-limb prosthesis users, and proposed diffusion-based zero-shot estimation as a potential remedy @zhouDiffusionModelsEnable2025. Cimorelli et al. addressed similar limitations in monocular gait analysis by training a custom DeepLabCut model, but did not evaluate sensitivity to controlled alignment perturbations or integrate the model into a multi-camera 3D reconstruction pipeline @cimorelliPortableInclinicVideobased2022. The present work builds on both contributions by embedding a prosthesis-specific model within a full multi-camera markerless pipeline and evaluating not only tracking accuracy but clinical sensitivity — the ability to detect biomechanically meaningful changes of the magnitude routinely encountered in clinical practice. The finding that the system preserves the direction and rank-ordering of alignment-induced changes across all three planes of adjustment suggests that, even where absolute accuracy remains imperfect, the system may be sufficient for the comparative judgment tasks that characterize clinical alignment assessment. 

The primary aim of this study was to characterize system accuracy and sensitivity to controlled alignment perturbations of known magnitude, a goal that is well-served by a within-participant repeated-measures design that eliminates inter-individual variability as a confound. However, this analysis focused on a single subject with transfemoral amputation, and it is thus not known yet whether our results will generalize to new subjects. Prosthesis users vary substantially in residual limb morphology, prosthetic componentry, gait compensatory strategies, and walking speed, all of which may affect pose estimation performance. Future work should evaluate system performance across a larger and more diverse cohort of prosthesis users, including individuals with transtibial amputation, bilateral amputation, and varying levels of ambulatory function. 

Our findings highlight the need for markerless motion capture software that can support task-specific pose estimation models when generic pose estimation fails for a specific population. However, training task-specific pose models typically requires technical knowledge and manual annotation, remaining a practical barrier to broader adoption of markerless motion capture in clinical and translational settings. The need for datasets based on diverse human demographics and anthropometry has previously been highlighted as a crucial step for the use of pose estimation software and markerless motion capture in a clinical setting @seethapathiMovementScienceNeeds2019 @needhamAccuracySeveralPose2021 @wadeApplicationsLimitationsCurrent2022. Several recent datasets have begun addressing pose estimation of individuals with amputations and prosthetic limbs @yinProGaitMultiPurposeVideo2025 @duInclusiveVidPoseBridgingPose2025 @yingLDPoseInclusiveHuman. In future work, pose estimation software trained on these datasets could be integrated into the markerless system pipeline to improve tracking of individuals with prosthetic limbs. 

