== Discussion


This study evaluated the sensitivity of a markerless motion capture system to gait changes resulting from controlled alignment adjustments to an above-knee prosthesis during treadmill walking. Although markerless motion capture using RTMPose and MediaPipe has previously been shown to capture lower-limb kinematics in able-bodied individuals @ceriolaComparativeAnalysisMarkerless2024, our findings suggest that these out-of-the-box pose estimation algorithms are not sufficient for motion capture of prosthesis users. In contrast, integrating a prosthesis-specific model into the pipeline substantially reduced joint position error and enabled detection of biomechanical changes associated with leg length adjustments, sagittal-plane knee and ankle kinematic changes and minimum toe clearance associated with ankle dorsiflexion/plantarflexion adjustments, and foot progression angle changes associated with toe-in/toe-out adjustments. Across alignment conditions, the markerless system preserved the ranking and directionality of the major biomechanical changes relative to the marker-based reference system, despite increased stride-to-stride variability.

The ability of the markerless system to distinguish changes in these metrics suggests that it may have utility in clinical alignment assessment. Prior work has indicated that leg length discrepancies as small as 5–10 mm can negatively impact prosthesis users @fodorCompensationLegLength2025 @gordonLegLengthDiscrepancy2019. Sagittal plane alignment deviations in persons with transfemoral amputation have been shown to elicit compensatory strategies, including increased hip extension moments and reduced step length, to maintain prosthetic knee stability @koehler-mcnicholasBiomechanicalResponsePersons2016.  Foot progression angle deviations are recognized clinically as a common gait deviation requiring alignment correction @hashimotoProperSequenceDynamic2023. Across all three planes, prosthetic malalignment in persons with transfemoral amputation has been linked to asymmetric loading on the intact limb and elevated long-term risk of osteoarthritis @zhangEffectProstheticAlignment2019, underscoring the clinical importance of detecting even subtle alignment deviations. 

The results of this study extend prior work on pose estimation for prosthesis users in two important respects. Zhou et al. demonstrated that standard OpenPose models produce substantial joint coordinate errors in lower-limb prosthesis users, and proposed diffusion-based zero-shot estimation as a potential remedy @zhouDiffusionModelsEnable2025. Cimorelli et al. addressed similar limitations in monocular gait analysis by training a custom DeepLabCut model, but did not evaluate sensitivity to controlled alignment perturbations or integrate the model into a multi-camera 3D reconstruction pipeline @cimorelliPortableInclinicVideobased2022. Here, we show that a multi-camera markerless pipeline integrated with a prosthesis-specific model preserves the direction and rank-ordering of alignment-induced changes across all three planes of adjustment, suggesting that, even where absolute accuracy remains imperfect, the system may be sufficient for the comparative judgment tasks that characterize clinical alignment assessment. 

Our findings highlight the need for markerless motion capture software that can support population-specific pose estimation models when generic pose estimation fails for a given user. In this study, a custom DeepLabCut model substantially improved prosthetic-limb tracking, but the need for manual annotation, technical expertise, and workflow customization makes this approach difficult to translate directly into routine clinical use. More broadly, this work demonstrates the utility of a modular markerless motion capture pipeline, implemented here using the FreeMoCap software, that can accommodate population-specific tracking needs rather than relying solely on a single out-of-the-box pose estimator. This flexibility may become increasingly valuable as more inclusive datasets and models emerge. Prior work has emphasized the need for datasets representing diverse human demographics, anthropometry, and clinical populations to support broader clinical use of pose estimation and markerless motion capture @seethapathiMovementScienceNeeds2019 @needhamAccuracySeveralPose2021 @wadeApplicationsLimitationsCurrent2022. Several recent datasets have begun addressing pose estimation of individuals with amputations and prosthetic limbs @yinProGaitMultiPurposeVideo2025 @yingLDPoseInclusiveHuman @duInclusiveVidPoseBridgingPose2025. As such models continue to develop, the pipeline framework used here provides a path for integrating them into multi-camera markerless motion capture workflows, potentially enabling improved prosthetic tracking in a more practical and scalable form.

The primary aim of this study was to characterize system accuracy and sensitivity to controlled alignment perturbations of known magnitude, a goal that is well-served by a within-participant repeated-measures design that eliminates inter-individual variability as a confound. However, this analysis focused on a single subject with transfemoral amputation, and it is thus not known yet whether our results will generalize to new subjects. Prosthesis users vary substantially in residual limb morphology, prosthetic componentry, gait compensatory strategies, and walking speed, all of which may affect pose estimation performance. Future work should evaluate system performance across a larger and more diverse cohort of prosthesis users, including individuals with transtibial amputation, bilateral amputation, and varying levels of ambulatory function. 

This study demonstrates that a markerless motion capture system can detect the biomechanical changes associated with specific prosthetic alignment adjustments - information that is currently unavailable in routine clinical care. Current clinical assessment relies on a range of outcome measures, from patient-reported questionnaires assessing perceived mobility to functional performance tests such as the 6-Minute Walk Test and Timed Up and Go. These measures are well-suited to appointment time constraints, but are limited in capturing the kinematic changes associated with specific alignment adjustments. Our findings suggest a path towards integrating objective biomechanical feedback into routine prosthetic care, helping to monitor patient progress across appointments, inform prosthetist alignment decisions, and provide objective biomechanical evidence to support payer justification for prosthetic components. Together, these possibilities highlight a longstanding gap between the biomechanical rigor of research settings and the practical realities of everyday clinical care. As markerless systems continue to develop, high-quality gait analysis could become a more practical component of routine prosthetic assessment.





