= Introduction B: Markerless Motion Capture

In 1983, David Hogg published a seminal work mapping a model made of a series of heirarchical cylinders onto an image of a person walking @hoggModelbasedVisionProgram1983. In 1996, Davis and Gavrila published one of the earliest multi-camera markreless motion capture software, mapped an articulated generalized cylindrical model onto images of a human using edge detection. We often state that markerless motion capture has advanced due to recent developments in pose estimation. Early markerless methods, lacking a method to accurately track anatomical landmarks from an image, would often first find the shape of the body itself - using methods such as optical flow tracking @marzani3DMarkerfreeSystem2001, 3D visual hull reconstruction @corazzaMarkerlessMotionCapture2006, or silleahoute extraction @rosenhahnSystemMarkerlessMotion2006. 

The recent advances in computer vision oft mentioned in markerless motion capture context came with the development and release of CNN-based models DeepPose @toshevDeepPoseHumanPose2014 and OpenPose @caoOpenPoseRealtimeMultiPerson2019, with deep-learning methods suddenly becoming state of the art @nagornyComprehensiveReviewRealTime2025. 


*The Microsoft Kinect: A case study in accessibility *

In 2010, Microsoft relased the Kinect, a gaming peripheral for the Xbox 360 that, unlike other gaming consoles, did not require a control. Instead, the Kinect worked using the dual use of infrared emitters and cameras to provide depth data, and RGB cameras to provide color, creating a 3D depth map in real-time @shottonRealTimeHumanPose. Although initially a commercial success, the forced adoption into the XBox platform and lack of games caused the Kinect eventually faded out of use before being officially discontinued in 2017 @pandeSlowPainfulDeath2023. One could look at this and call the Kinect a long-term failure. 

This however, does not account for the massive impact a gaming device had on the research and academic field. The Kinect was the first time technology that typically cost tens of thousands of dollars was neatly packaged for \$150, particularly in the pre-deep learning revolution era, and many developers saw the potential in this software. The Kinect was hacked and within days of its release, with Adafruit posting a \$3000 bounty for the first person to do so @adafruitOpenKinectProject2010, and open-source drivers for PC use appeared within weeks (an interesting note here is that this contest was proposed to Adafruit by a core developer on the Kinect, who was frustrated with Microsoft's reluctance to offer any PC support @KinectDeveloperClaims). The Kinect suddenly saw use across many fields - for example being integrated into robotics to enable low-cost mapping and navigation @el-laithyStudyUseMicrosoft2012. Depsite initial resistance, Microsoft eventually released a developer kit in 2012, after which the Kinect saw a sudden widespread of use in biomechanical research. Numerous studies exist detailing the use of the Kinect for clinical and research use @ValidityMicrosoftKinect2012 @jebeliStudyValidatingKinectV22017 @yeungEvaluationMicrosoftKinect2014. Even though several limitations @pfisterComparativeAbilitiesMicrosoft2014 (e.g. occlusion causing major issues due to the single camera view point) were identified, the cost and availability of the system made it one of the first available-to-researchers systems to take something very costly and do it for much less. Even after Microsoft discontinued the Kinect for gaming, they released it under the Azure Development Kit for a few years after. Eventually however, this was discontinued as well.

I go through the history and use of a defunct system here because I believe ultimately, even in its eventually failure continue to be in use, this story neatly illustrates the needs of the research and clinical community. There is a significant need for an available, low-cost system that researchers can use and adapt to their own purposes - one that cannot simply be 'discontinued'. 


*Benefits of markerless motion capture*

Markerless motion capture has held much promise for research and clinical work because it has the potential to provide data on-par with marker-based motion capture, with the affordability and convenience of IMUs/accelerometers. 

However, even current markerless motion capture systems are limited in use. Commercial systems like Theia Markerless remain out of use for the ground-level user, while others are constrained to specific applications, making adaptation across diverse clinical and research environments different. 

This persistent tradeoff between accuracy, accessibility and adaptability limits the broader impact of motion capture technology, and thus there is a need for a system that can address these limitations. 

This work encompasses the development and validation of FreeMoCap, a free open-source motion capture software designed to simultaneously achieve accuracy through advanced computer vision, accessibility through use of low-cost hardware, and adaptability through modular software design. 