== Quantitative motion analysis: Understanding the mechanisms of movement

It is very easy for us to overlook the complexities of a simple action such as standing up. And yet even the act of rising from a chair utilizes dozens of muscles and joints across the entire body, all working to execute a series of complex movements that shift the body's center of mass from a stable seated position into less stable standing posture - smoothly, quickly and without falling over @liKinematicAnalysisHuman2021. Even an action this mundane can tell us a great deal. The time it takes someone to stand up from a chair five times is in fact a validated clinical assessment of functional health @FiveTimesSit2013. This pattern is true of a great deal of movements - walking, balancing, reaching - embedded within these movements is information that provides a window into the inner workings of the body. 

Quantitative motion analysis is, then, the process of turning movement into measurement and extracting meaningful parameters from it. One familiar form of this might be checking your daily step count on your phone - this is the result of raw accelerometer and gyroscope signals being transformed into a meaningful metric. In research and clinical work, such methods are critical to further understanding the biomechanics of human movements, from gait and posture to athletic performance. There are many standard methods of measuring movement, and of these methods, one is particularly relevant to this work: marker-based motion capture.

== Marker-based motion capture

Marker-based motion capture systems provide measurements of 3D joint locations by tracking reflective markers placed on anatomical landmarks using multiple infrared cameras. The broad use of marker-based motion capture demonstrates the utility of 3D data across a multitude of domains - such as aiding in special effects for film and animations, or training robotic motion @menolottoMotionCaptureTechnology2020. In research and clinical settings however, marker-based motion capture serves a different purpose - as a gold-standard method of quantitative movement analysis that provides precise biomechanical measurements of how the body moves @colyerReviewEvolutionVisionBased2018.  


== Quantitative motion analysis in research

Marker-based motion capture can track movement with high precision and accuracy, providing detailed kinematic measurements that have become a fundamental aspect of biomechanical research - from understanding joint mechanics and muscle coordination patterns @vanderheijdenMusclesLimitingSittostand2009 to evaluating the effects of surgical intervention @christiansenWeightBearingAsymmetrySitStand2011 and prosthetic alignment @baldockDetectingInteradjustmentCoupling2025. When used in tandem with force plates and EMG sensors, the combination of kinematic, kinetic and muscle activation data can allow for comprehensive understanding of motor control and muscle activity @delpOpenSimOpensourceSoftware2007. 

Despite being a gold-standard in the field, there are important accuracy limitations to consider when evaluating marker-based motion capture data. Accuracy is affected by the exact placement of markers on anatomical landmarks. Marker placement requires training, and the experience level of the researcher doing so can impact placement reliability and accuracy @sinclairInfluenceTesterExperience2014. Markers are also prone to what are known as soft tissue artifacts, where the movement of skin over the bone itself introduces errors into kinematic tracking @camomillaHumanMovementAnalysis2017. 

Additionally, marker-based motion capture constrains studies to the laboratory environment. 
Measurements taken in a lab environment may not reflect day-to-day functionality, as the environment itself can impose pressure or limitations that influence behavior.@AnalyzingGaitReal@ojedaInfluenceContextualTask2015 @rantakokkoGaitFeaturesDifferent2024 @hahmInhomeHealthMonitoring2022. Additionally, markers themselves can inhibit natural movement @colyerReviewEvolutionVisionBased2018. As a result, there has been growing interest in understanding movement outside of controlled laboratory environments. Understanding movement in the real world has become a widely researched topic (e.g., assessing independence and health risks in the elderly @yangRemoteMonitoringAssessment2012 or understanding the coordination of visual and locomotor systems in outdoor terrain @matthisGazeControlFoot2018). Detailed kinematic data could further this understanding, but there is a gap in methods available to provide this data in real world environments @weiMotionTrackingDaily2024. Thus, there is a need for technology that can return detailed kinematic data of natural behavior and operate outside of the laboratory environment.


*(A brief aside on 'gold-standards' for measuring movement)*

While throughout this work, marker-based motion capture will be referred to as a 'gold-standard', it should be noted that one of the most accurate methods of measuring and evaluating joint function to date is biplanar videoradiography. Biplanar videoradiography is a method of mapping the pose of 3D bone models using synchronized x-ray image sequences of motion with sub-millimeter accuracy @kesslerDirectComparisonBiplanar2019, with joint tracking errors ranging from 0.25-0.30mm for the foot @mirandaStaticDynamicError2011. Despite this method's high accuracy, its cost, lack of whole-body kinematics, and complicated setup make biplanar videoradiography impractical for widespread adoption in research and clinical contexts@wadeApplicationsLimitationsCurrent2022.


== Quantitative analysis in clinical work
In a clinical space, quantifying movement can inform diagnosis, increase understanding of disease progression and severity, and evaluate rehabilitation or therapy efficacy @buckleyRoleMovementAnalysis2019@vanierselSystematicReviewQuantitativeclinical2004@vergheseQuantitativeGaitDysfunction2007@SummaryMeasuresClinical2014 @kerrAdoptionStrokeRehabilitation2018 (see Chapter 3: Introduction and Chapter 4: Introduction for examples specific to gait and posture). Although research environments may make use of marker-based motion capture, force plates, and EMG sensors to return comprehensive movement data, methods of measuring movement in clinical work tend to be altogether simpler and more practical. 

Many clinicians tend to use subjective methods to analyze patient motion, often involving self-reporting or observation @sharmaFactorsInfluencingClinical2024. The Berg Balance Scale @bergMeasuringBalanceElderly1989 for example, is a test that assesses dynamic and static balance that has been used to evaluate fall risk and to assess stroke patient recovery. This test involves grading 14 tasks on a 5-point scale based on factors such as dependence on external supervision or assistance and time to complete the task @mirandaBergBalanceTesting2026. Another example is the Tinetti Test @tinettiPerformanceOrientedAssessmentMobility1986 which assesses both posture and gait to identify fall risk in populations such as the elderly, stroke, and PD patients. While these tests are widely used and reliable, accuracy can be dependent on clinician experience @nishiguchiReliabilityValidityGait2012 and the kind of movement being observed@maclachlanOBSERVERRATINGTHREEDIMENSIONAL2015. 

In terms of quantitative analysis, some clinics may use gait mats or force plates, but for many clinics assessments may only require tools as simple as a stopwatch  (e.g., the Timed Up and Go Test). Use of tools in a clinic is largely a practical choice, with Kerr et al. describing access, ease of use and value for money as key needs in adopting technology for clinical use @kerrAdoptionStrokeRehabilitation2018 and Buckley et al. describing the tradeoff between the desire for more detailed methods of analysis and the complexity of using such means in a clinic @buckleyRoleMovementAnalysis2019. There is a large disparity between the methods used for analysis of human motion in a laboratory and what can be feasibly used in a clinic @vanierselSystematicReviewQuantitativeclinical2004 @buckleyRoleMovementAnalysis2019.

Often, research into quantitative methods for clinical use examines adopting practical everyday technology to provide data, such as using smartphone accelerometers for gait analyses @grouiosAccelerometersOurPocket2022@nishiguchiReliabilityValidityGait2012. While accelerometers are relatively inexpensive and easy to use, extraction of meaningful data from their signals can be difficult @ClinicalApplicationsSensors. A means of augmenting clinician care with detailed quantitative data could help track trends over time, provide precise feedback on care, and also provide justification to insurance for reimbursement @parksCurrentLowCostVideoBased2019. 

Although marker-based motion capture does provide detailed, meaningful kinematic data, it is ill-suited to the task of everyday clinical use. Marker-based motion capture is expensive, and the cost alone is usually enough of a barrier to prevent adoption @parksCurrentLowCostVideoBased2019 @sharmaFactorsInfluencingClinical2024. Marker-based motion capture also requires specialized hardware, space and trained users to be able to operate and clean the data @parksCurrentLowCostVideoBased2019, limiting adoption in clinical spaces @buckleyRoleMovementAnalysis2019 @ClinicalApplicationsSensors. Marker-placement also may not be suitable for certain patient populations @wadeApplicationsLimitationsCurrent2022. As such, these systems typically remain accessible only to specialized hospitals and research groups with the financial resources and infrastructure to support it. 

Thus, there is a need for accessible technology that can be accurate and feasible to use in a clinical setting. 

== The need: a more accessible method of measuring kinematic data

In examining the research and clinical spaces, we see different, yet related, needs emerge. In the research space, there is a need to facilitate motion analyses in ways that do not constrain natural behavior and operate in the real world, while in clinical spaces we see that reliable access to detailed methods of quantitative motion analysis could augment clinical decision making, but current solutions still force a tradeoff between depth of data and practicality. 

Across both domains, a common need emerges: high-resolution kinematic data without laboratory constraints. Emerging advances in computer vision have positioned markerless motion capture as a potential solution to this need. The following chapter examines the current landscape of markerless motion capture technology and the limitations that remain in realizing this potential.



