
Mundane actions can tell a story about human health. Even the act of rising from a chair involves a series of complex movements that shift the body's center of mass from a stable seated position into less stable standing posture - smoothly, quickly and without falling over @liKinematicAnalysisHuman2021. The time it takes someone to stand up from a chair five times is, in fact, a validated clinical assessment of functional health @FiveTimesSit2013. This pattern is true of a great deal of movements - walking, balancing, reaching - embedded within these movements is information that provides a window into the inner workings of the body. 

Quantitative motion analysis is, then, the process of turning movement into measurement and extracting meaningful parameters from it. 

Gait, for example, is a highly coordinated and optimized process, governed by principles that shape its stability and efficiency, and disruptions to this efficiency can manifest as pathological gait @kuoDynamicPrinciplesGait2010. As such, gait can be a highly informative window into health, changing recognizably in response to disease and functional decline (e.g., cautious, stiff-legged or freezing patterns) @osobaBalanceGaitElderly2019. For example, gait speed at midlife has been linked to cognitive function and decline @rasmussenAssociationNeurocognitivePhysical2019, characteristics of gait dysfunction can differentiate between different types of dementia @vergheseQuantitativeGaitDysfunction2007, and early gait abnormalities have been used to help diagnose PD @galnaProgressionGaitDysfunction2015 and predict decline in attention and memory @morrisGaitRatherCognition2017. 

Similarly, balance is a series of adjustments that result from the continuous coordination of visual, vestibular, and neuromuscular systems @horakClinicalAssessmentBalance1997. Assessments of balance can be useful for diagnosis (e.g., early detection of fall risk in individuals @manciniRelevanceClinicalBalance2010) or in rehabilitation (e.g, tailoring treatment strategies to the individual @visserClinicalUtilityPosturography2008). 

The gold standard for accurate measurements of kinematic data is marker-based motion capture. When used in tandem with force plates and EMG sensors, the combination of kinematic, kinetic and muscle activation data can allow for comprehensive understanding of motor control and muscle activity @delpOpenSimOpensourceSoftware2007. However, accuracy is affected by the exact placement of markers on anatomical landmarks. Marker placement requires training, and the experience level of the researcher doing so can impact placement reliability and accuracy @sinclairInfluenceTesterExperience2014. Markers are also prone to what are known as soft tissue artifacts, where the movement of skin over the bone itself introduces errors into kinematic tracking @camomillaHumanMovementAnalysis2017. Additionally, marker-based motion capture constrains studies to the laboratory environment. 
Measurements taken in a lab environment may not reflect day-to-day functionality, as the environment itself can impose pressure or limitations that influence behavior.@AnalyzingGaitReal@ojedaInfluenceContextualTask2015 @rantakokkoGaitFeaturesDifferent2024 @hahmInhomeHealthMonitoring2022. Additionally, markers themselves can inhibit natural movement @colyerReviewEvolutionVisionBased2018. Currently, there is a gap in the methods available to provide detailed kinematic data in real world environments @weiMotionTrackingDaily2024. 

Additionally, marker-based motion capture is ill-suited to the task of everyday clinical motion capture. Methods of measuring movement in clinical work tend to be altogether simpler and more practical. Many clinicians tend to use subjective methods to analyze patient motion, often involving self-reporting or observation @sharmaFactorsInfluencingClinical2024 @bergMeasuringBalanceElderly1989 @tinettiPerformanceOrientedAssessmentMobility1986. While these tests are widely used and reliable, accuracy can be dependent on clinician experience @nishiguchiReliabilityValidityGait2012 and the kind of movement being observe d@maclachlanOBSERVERRATINGTHREEDIMENSIONAL2015.  many clinics, assessments only require tools as simple as a stopwatch  (e.g., the Timed Up and Go Test). Use of tools in a clinic is largely a practical choice, with Kerr et al. describing access, ease of use and value for money as key needs in adopting technology for clinical use @kerrAdoptionStrokeRehabilitation2018 and Buckley et al. describing the tradeoff between the desire for more detailed methods of analysis and the complexity of using such means in a clinic @buckleyRoleMovementAnalysis2019. There is a large disparity between the methods used for analysis of human motion in a laboratory and what can be feasibly used in a clinic @vanierselSystematicReviewQuantitativeclinical2004 @buckleyRoleMovementAnalysis2019. A means of augmenting clinician care with detailed quantitative data could help track trends over time, provide precise feedback on care, and also provide justification to insurance for reimbursement @parksCurrentLowCostVideoBased2019. 

Thus, there is a need for accessible technology that can be accurate and feasible to use in a clinical setting. 

The Free Motion Capture Project (FreeMoCap) @queenFreeMoCapFreeOpen2024 is a free, open-source motion capture system that reconstructs 3D kinematic data from synchronized videos using consumer-grade webcams (see Chapter 3). By relying on low-cost hardware and open-source software, FreeMoCap lowers barriers to adoption in both clinical and research settings. Its modular architecture also enables integration and comparison of multiple pose estimation backends within the same reconstruction pipeline, enabling detailed benchmarking of tracking algorithm performance and accuracy. 

Here, we validate the FreeMoCap system on gait and balance tasks. 
'



Markerless motion capture offers an accessible approach for obtaining such measurements outside of specialized laboratory environments. arly markerless systems shared a common constraint. Without the ability to directly identify anatomical features in an image, they had to work with the data they could extract: the shape of the body itself using techniques such as edge detection @gavrila3DModelbasedTracking1996, optical flow tracking @marzani3DMarkerfreeSystem2001, silhouette extraction @rosenhahnSystemMarkerlessMotion2006, and 3D visual hull reconstruction @corazzaMarkerlessMotionCapture2006. While these methods could estimate body position in space, they were complex, often computationally intensive methods that required significant expertise to implement. 

A fundamental shift towards modern markerless motion capture occurred with the introduction of deep learning-based pose estimation. 
The release of DeepPose @toshevDeepPoseHumanPose2014 in 2014 and OpenPose@caoOpenPoseRealtimeMultiPerson2019 in 2017 marked a transition point, giving researchers access to methods that could learn to infer joint locations directly. With this, deep-learning methods became state-of-the-art and the dominant approach to markerless motion capture @nagornyComprehensiveReviewRealTime2025. 

Pose estimation has become a fundamental part of markerless motion capture. However, different pose estimation sfotware have different strengths and weaknesses, and the performance of a given pose estimation model can vary across different tasks and populations. For example, models trained on able-bodied individuals may struggle to track individuals with altered limb morphology, such as limb amputations @zhouDiffusionModelsEnable2025 @cimorelliPortableInclinicVideobased2022. As such, there is a need for markerless motion capture systems that can support interchangeable pose estimation backends, allowing researchers to select or compare algorithms that might be better suited to specific populations or research needs.





It is very easy for us to overlook the complexities of a simple action such as standing up. And yet the act of rising from a chair utilizes dozens of muscles and joints across the entire body, all working to execute a series of complex movements that shift the body's center of mass from a stable seated position into less stable standing posture - smoothly, quickly and without falling over @liKinematicAnalysisHuman2021. Even an action this mundane can tell us a great deal. The time it takes someone to stand up from a chair five times is, in fact, a validated clinical assessment of functional health @FiveTimesSit2013. This pattern is true of a great deal of movements - walking, balancing, reaching - embedded within these movements is information that provides a window into the inner workings of the body. 

Quantitative motion analysis is, then, the process of turning movement into measurement and extracting meaningful parameters from it.  Marker-based motion capture remains the gold-standard for capturing accurate kinematic data, but is generally unsuitable for widespread clinical use (see Chapter 1). 

Markerless motion capture offers an accessible approach for obtaining such measurements outside of specialized laboratory environments. However, existing systems may be limited by cost, hardware requirements or methodological constraints (see Chapter 2). 

The Free Motion Capture Project (FreeMoCap) @queenFreeMoCapFreeOpen2024 is a free, open-source motion capture system that reconstructs 3D kinematic data from synchronized videos using consumer-grade webcams (see Chapter 3). By relying on low-cost hardware and open-source software, FreeMoCap lowers barriers to adoption in both clinical and research settings. Its modular architecture also enables integration and comparison of multiple pose estimation backends within the same reconstruction pipeline, enabling detailed benchmarking of tracking algorithm performance and accuracy. 


Gait: 
It is a highly coordinated and optimized process, governed by principles that shape its stability and efficiency, and disruptions to this efficiency can manifest as pathological gait @kuoDynamicPrinciplesGait2010. As such, gait can be a highly informative window into health, changing recognizably in response to disease and functional decline (e.g., cautious, stiff-legged or freezing patterns) @osobaBalanceGaitElderly2019. For example, gait speed at midlife has been linked to cognitive function and decline @rasmussenAssociationNeurocognitivePhysical2019, characteristics of gait dysfunction can differentiate between different types of dementia @vergheseQuantitativeGaitDysfunction2007, and early gait abnormalities have been used to help diagnose PD @galnaProgressionGaitDysfunction2015 and predict decline in attention and memory @morrisGaitRatherCognition2017.

Balance:
These adjustments result from the continuous coordination of visual, vestibular, and neuromuscular systems @horakClinicalAssessmentBalance1997. 

Assessments of balance can be useful for diagnosis (e.g., early detection of fall risk in individuals @manciniRelevanceClinicalBalance2010) or in rehabilitation (e.g, tailoring treatment strategies to the individual @visserClinicalUtilityPosturography2008). Clinical assessments of balance tend to be limited to practical, easily useable methods @manciniRelevanceClinicalBalance2010 @bergMeasuringBalanceElderly1989 @tinettiPerformanceOrientedAssessmentMobility1986. The Modified Clinical Test of Sensory Interaction on Balance (CTSIB-M) @ModifiedClinicalTest2013, for example, only requires a foam balance pad and a stopwatch. In this test, participants maintain balance under four conditions that systematically vary visual input and surface stability (eyes open/closed; firm/foam surface). Test scores are based on how long the participant is able to maintain each condition.

Although qualitative and simple quantitative methods like these may be reliable and practical, they may not be enough to fully grasp the complex motor skills that underlie balance @paillardTechniquesMethodsTesting2015 @visserClinicalUtilityPosturography2008, while also suffering from tester bias @manciniRelevanceClinicalBalance2010. Detailed quantitative analysis could provide valuable insight into patient balance, noting subtle trends that visual assessment may miss, and providing objective metrics of individual trends in balance over time, whether during aging or injury recovery.


==

The Free Motion Capture Project (FreeMoCap) @queenFreeMoCapFreeOpen2024 is a free, open-source motion capture system that reconstructs 3D kinematic data from synchronized videos using consumer-grade webcams (see Chapter 3). By relying on low-cost hardware and open-source software, FreeMoCap lowers barriers to adoption in both clinical and research settings. Its modular architecture also enables integration and comparison of multiple pose estimation backends within the same reconstruction pipeline, enabling detailed benchmarking of tracking algorithm performance and accuracy. 

Here, we use the FreeMoCap system, a free, open-source motion capture system to measure postural metrics in participants completing the CTSIB-M. The contributions of this work are three-fold: first, this chapter examines the accuracy and sensitivity of the system to subtle postural changes across progressively difficult conditions in comparison to a marker-based reference; second, this work examines the ability of markerless motion capture to be used for the CTSIB-M test, which has yet to be evaluated for this kind of system; third, this work characterizes the performance of three different pose estimation backends, MediaPipe, RTMPose and ViTPose during balance assessment. 