== Discussion

*Joint center and joint kinematic accuracy*

Reconstructed joint centers were generally under 30mm, with lowest error across the mediolateral axes. The hip joint center was generally the biggest source of error, with an RMSE of ~20mm in the anterior-posterior and vertical axes across speed. Kinematic error tended to be under 5°, with error errors only occurring for the ViTPose-tracked ankle angle at higher speeds. 

These metrics sit well within the limits found by other studies, with errors similar to and under what was found by Ripic et al. @ripicComparisonThreedimensionalKinematics2023. The hip is generally a known point of difficult to track, with Kanko et al. noting a 3D Euclidean error of 36mm in the hip position and an 11° difference in hip/flexion extension @kankoConcurrentAssessmentGait2021 and Needham et al. noting systematic differences in hip and knee position tracking (~30-50mm) @needhamAccuracySeveralPose2021. Marker-based motion capture can also have an error range of about 25-30mm (find sources).  McGinley et al. also suggest that errors between 2-5° are suitable for clinical use @mcginleyReliabilityThreedimensionalKinematic2009.  

SPM testing shows consistent suprathreshold clusters in early stance phase in knee and ankle kinematics across all speeds. These clusters are positioned consistently with the loading response phase of gait, where the knee undergoes transient flexion as a method of shock absorption and the ankle plantarflexes slightly in the first rocker phase. Thus, it is possible that these motions may be difficult for pose estimation software to track correctly. Additionally, heel strike and the resulting absorption of impact has been shown to cause skin surface movement that propogates throughout the lower limb @painSoftTissueMotion2002. Skin-tissue artifacts are a known limitation of marker-based software - and as such a reminder that while our markerless system comparisons are in reference to a gold-standard method, it is not necessarily representative of true joint centers and their resulting kinematics, but rather the most accurate and available method we have to reconstruct them. 

*Gait parameter accuracy*

Generally, gait parameters show minimal bias and excellent agreement with the reference. Limits of agreement (LoA) for stride and step length pooled over all walking speeds are within approximately ±70mm for all pose estimation backends, and LoA for stance and swing duration within ±40ms for RTMPose and ViTPose and within ±70ms for MediaPipe. We found that lowest agreement was with swing phase (ICC = \~.90). These findings align closely with findings by Kanko et al., who found LoA to be within ±70mm for stride and step length, stance time within -40 - 70ms, and swing time within -70 to 40ms, with low agreement in swing phase (ICC = .39) for participants at a self-selected walking speed @kankoAssessmentSpatiotemporalGait2021. The foot is moving at its fastest in swing phase, and lower agreement could be a result of our framerate (30Hz). Higher framerate cameras would be able to capture smaller changes in foot position during periods of high velocity motion. A limitation of our temporal metrics is that error is discretized to 33ms increments (our framerate), which could obscure some error. Higher framerate cameras could provide a deeper level of insight and resolution into temporal metrics.  

Clinically, we can compare bland-altman to minimal detectable change values to assess whether our markerless setup would have the resolution to dscriminate between impaired and healthy populations. add some notes about some mdcs from papers. 

*Impact of speed*

Walking speed has a variable impact on the data. Generally, hip joint position error and hip angle error was not affected by speed. While joint position error in the ML axis was consistent across speed, ankle and toe joint center error increased with speed (i.e. Approximate RTMPose RMSE range from slowest to fastest speed, ankle: 9-16mm, toe:10-23mm) across the AP axis, and knee and ankle joint center increased across the ML axis (ie.e. Approximate RTMPose range from slowest to fastest speed: knee: 11-17, toe: 7-17mm), while the ankle error remained relatively consistent. Saggital knee and ankle angles also increased with speed (i.e. approximate RTMPose error from slowest to fastest speed, knee: 2.2-3.6°, ankle:1.6-3.2°). Joint angle error could be a result of the propogating positional error in trajectories. 

Speed had an asymmetric impact on spatiotemporal gait parameters. When spatial gait metrics were stratified by speed, LoA across all trackers widened with faster movement (i.e. approximate ViTPose LoA from slowest to fastest speed: ±19mm to ±88mm). Step length agreement decreased substantially with speed as opposed to stride length, which showed only a slight decrease. Temporal gait metric LoA were generally not impacted by speed, remaining relatively stable across all speeds, although for both stance and swing duration, agreement with the reference decreased substantially across speed.  

[something about why this is important]

*Impact of tracker*

Generally, all tracker-derived data closely aligned with the reference data. However, tracker behavior often showed systematic differences. Gait event timing for all trackers tended to fall within one frame of error. 

We found that ViTPose-derived 3D data was consistently overscaled compared to the reference marker-based data by about 2-3%. However, this scaling was invariate. Substantially higher joint trajectory was noted in the vertical axis as opposed to the AP or ML axes. As a result, the spatial parameters derived in this study, which were both calculated in the direction of walking (AP axis), were largely unaffected by the scaling.  However, care would need to be taken with calculating gait parameters that may depend on different axes (such as minimum toe clearance, which is the vertical height between the foot and the floor at the lowest point of swing) as we might expect the scaling to impact ViTPose accuracy to the reference (and real-world) distances measured. ViTPose generally demonstrated the smallest bias and difference from the reference in gait metrics. ViTPose generally had the lowest error in tracking hip and knee angles. While ankle angles were still under 7°, ViTPose-derived angles overshoot peak plantarflexion and SPM shows suprathreshold clusters across nearly the entire gait cycle, with a near consistent offset observed in gait cycle-normalized joint angles. This offset may be due to the vertical axis in the toe, as a consistent positional error could cause consistent angle error. 

MediaPipe-derived 3D data was generally accurate in joint trajectories and joint kinematics. However, SPM analysis of hip and knee angles shows consistent speed dependent error - with suprathreshold clusters surrounding peak hip extension and peak knee flexion that decrease across walking speed. Notably, these errors are not at the peaks themselves, but before and following them. MediaPipe also shows a consistent underestimation of peak plantarflexion. With spatiotemporal parameters, MediaPipie generally showed the widest LoA, although agreement was generally comparatble to other trackers at all speeds. Speed-dependant changes in MediaPipe could be a result of the one-euro filter @casiez1FilterSimple2012, an adaptive-low pass filter that lowers the cutoff frequency at lower speeds, reducing jitter at the expense of lag, while increasing the cutoff frequency at higher speeds to reduce lag. The larger errors at slower walking speeds, particularly in large flexion/extension movements, could be an artifact of the lag produce by the one euro filter adapting to changes in velocity from a slower movement. 

RTMPose was generally consistent across scaling, joint kinematics, and spatiotemporal parameters, while also showing the most accurate tracking of ankle kinematics.

Thus, RTMPose may be the best option for gait analysis. ViTPose may be an alternative option where scaling is not a concern. MediaPipe, with not requiring a GPU to use, remains a widely accessible option for all user, but with some systematic error to be aware of in its usage for gait analysis. 