== Discussion

*Accuracy in joint kinematics*

Average joint position error generally tended to be under 30mm, with the lowest error in the medio-lateral direction and highest in the anterior-posterior direction. These differences are comparable to results from previous studies. Nakano et al. found RMSE's generally under 30. Both trajectories and kinematic errors were similar to and under the findings by Ripic et al. @ComparisonThreedimensionalKinematics2023. Kinematic findings were on par with Theia (though we had lower for the hip and ankle) @kankoConcurrentAssessmentGait2021. We're also on par with OpenCap @uhlrichOpenCapHumanMovement2023. 
McGinley et al. suggest that kinematic errors between 2-5 degrees are suitable for clinical use @mcginleyReliabilityThreedimensionalKinematic2009. Needham et al. also observed systematic differences at the knee and hip @needhamAccuracySeveralPose2021.

(cite other freemocap validations?) (find some stuff regarding error acceptable limits)

Joint angle SPM testing also reports consist phase-specific error. During loading response after initial contact, the knee undergoes transient flexion is it absorbs shock and the ankle plantarflexes slightly (heel rocker). For the ankle, these regions correspond to the ankle plantarflexion that occurs during the loading response as it absorbs shock. Across all speeds, consistent suprathreshold clusters are noted for the knee and angle during this flexion and plantarflexion respectively. This suggests that the loading response in in gait is a period of higher reconstruction error. One possible explanation is that for a camera with a given sagittal (or close to sagittal view) of a participant, when the contralateral foot is in loading response, the ipsilateral foot closer to the camera is swinging past the contralateral leg, occluding it and potentially contributing to reconstruction error. Additionally, heel strike causes skin surface movement that propogates throughout the lower limb @painSoftTissueMotion2002 which could lead to soft tissue artifacts, a known limitation of marker-based software, meaning the reference might not be entirely accurate here as well. 

Some kinematic error appeared to be speed-dependent, decreasing as walking speed increased. This was most commonly seen in MediaPipe - particularly before and after peak hip extension and peek knee flexion. MediaPipe, in it's 'video' mode uses a one-euro filter @casiez1FilterSimple2012, an adaptive low pass filter than adapts cutoff frequency according to speed. Low speeds use a lower-cutoff frequency to reduce jitter at the expense of lag, while high speeds cutoff increases to reduce lag. The larger MediaPipe errors at slower walking speeds could be an artifact of the lag introduced by the one-euro filter adapting to slow movement with a lower-cutoff frequency, while error decreases as walking speed increases due to the filter iontroducing less temporal lag. 

Kinematic error at the angle was also heavily driven by tracker-dependent differences. MediaPipe consistently underestimated peak plantarflexion while ViTPose overestimated it. RTMPose slightly overestimated plantarflexion but was generally the most accurate. Systematic behavior differences can be seen in late swing of the ankle. MediaPipe plantarflexes rapidly while ViTPose dorsiflexes. Overall, RTMPose is the most accurate at tracking ankle kinematics. The ankle segment is relatively small, and therefore small positional errors could propogate into joint kinematics.   



*Spatiotemporal gait parameters*

Generally, temporal and spatial parameters measured by the markerless system were reported with minimal bias and strong agreement. As a whole, ViTPose showed the least bias and excellent agreement across parameters of each pose estimation backend. 

Limits of agreement (LoA) for spatial metrics generally increased with speed while remaining stable for temporal metrics. However, agreement across all parameters tended to drop with speeds, with sharp declines for step length and swing duration. Generally, spatial resolution is limited by the framerate of the cameras (30Hz). Higher framerate cameras might provide better capture of positioning of spatial limbs. Additionally, while temporal data was general table, metrics are were discretized to be within .33ms of each other. Thus, higher framerate might also allow for more detailed analysis of temporal metrics. 

Our gait parameter findings match well with others. Kanko et al. found that swing time also showed the least agreement (ICC =.39), LoA for step and stride length were found to be within ± 70mm, stance time within -40 - 70ms, and swing time within -70 to 40ms @kankoAssessmentSpatiotemporalGait2021. This is similar to and within the limits of our pooled data, and our data up to 1.5m/s for spatial metrics, and our data up to 2.5m/s for temporal metrics.  Vafadar et al. found LoA within approximately ±16mm for stride and steplength, and ±15ms for stance and swing time for participants walking at a self-selected comfortable speed @vafadarAssessmentNovelDeep2022. This is way better than what we had. Idk what to make of that. The only comparable parts are potentially our spatial metrics at 0.5m/s. 

Clinically, we can compare bland-altman to minimal detectable change values to assess whether our markerless setup would have the resolution to dscriminate between impaired and healthy populations. add some notes about some mdcs from papers. 


*Tracker Comparison*
something about how ViTPose is worse with scaling, but seems to have the lowest bias for parameters. That might be a bit weird because with scaling we might expect the spatial metrics to also suffer - but looking at the trajectory rmses, most obvious 'VitPose is different than the rest' error is in the Z direction - and these psatial metrics are in the A-P direction. If we look at something like minimum toe clearance however, it might be affected. The ankle joint kinematics for ViTPose however, might be so different because the Z error for the toe is noticeably higher, which would affect the angle as the segment is pretty small, so those errors propogate. MediaPipe has the high error issues in joint kinematics, and the widest LoA in gait parameters. Overall, RTMPose shows the most accurate ankle kinematics while also having accurate spatiotemporal parameters and still having 'true-to-scale' reconstruction - so this might be the best wholecale reconstruction option for gait? 







-- redo

*Joint center and joint kinematic accuracy*

Reconstructed joint centers were generally under 30mm, with lowest error across the mediolateral axes. The hip joint center was generally the biggest source of error, with an RMSE of ~20mm in the anterior-posterior and vertical axes across speed. Kinematic error tended to be under 5°, with error errors only occurring for the ViTPose-tracked ankle angle at higher speeds. 

These metrics sit well within the limits found by other studies, with errors similar to and under what was found by Ripic et al. @ripicComparisonThreedimensionalKinematics2023. The hip is generally a known point of difficult to track, with Kanko et al. noting a 3D Euclidean error of 36mm in the hip position and an 11° difference in hip/flexion extension @kankoConcurrentAssessmentGait2021 and Needham et al. noting systemic differences in hip and knee position tracking (~30-50mm) @needhamAccuracySeveralPose2021. Marker-based motion capture can also have an error range of about 25-30mm (find sources).  McGinley et al. also suggest that errors between 2-5° are suitable for clinical use @mcginleyReliabilityThreedimensionalKinematic2009.  

SPM testing shows consistent suprathreshold clusters in early stance phase in knee and ankle kinematics across all speeds. These clusters are positioned consistently with the loading response phase of gait, where the knee undergoes transient flexion as a method of shock absorption and the ankle plantarflexes slightly in the first rocker phase. Thus, it is possible that these motions may be difficult for pose estimation software to track correctly. Additionally, heel strike and the resulting absorption of impact has been shown to cause skin surface movement that propogates throughout the lower limb @painSoftTissueMotion2002. Skin-tissue artifacts are a known limitation of marker-based software - and as such a reminder that while our markerless system comparisons are in reference to a gold-standard method, it is not necessarily representative of true joint centers and their resulting kinematics, but rather the most accurate and available method we have to reconstruct them. 

*Gait parameter accuracy*

Generally, gait parameters show minimal bias and excellent agreement with the reference. Limits of agreement (LoA) for stride and step length pooled over all walking speeds are within approximately ±70mm for all pose estimation backends, and LoA for stance and swing duration within ±40ms for RTMPose and ViTPose and within ±70ms for MediaPipe. We found that lowest agreement was with swing phase (ICC = \~.90). These findings align closely with findings by Kanko et al., who found LoA to be within ±70mm for stride and step length, stance time within -40 - 70ms, and swing time within -70 to 40ms, with low agreement in swing phase (ICC = .39) for participants at a self-selected walking speed @kankoAssessmentSpatiotemporalGait2021. The foot is moving at its fastest in swing phase, and lower agreement could be a result of our framerate (30Hz). Higher framerate cameras would be able to capture smaller changes in foot position during periods of high velocity motion. A limitation of our temporal metrics is that error is discretized to 33ms increments (our framerate), which could obscure some error. Higher framerate cameras could provide a deeper level of insight and resolution into temporal metrics.  

Clinically, we can compare bland-altman to minimal detectable change values to assess whether our markerless setup would have the resolution to dscriminate between impaired and healthy populations. add some notes about some mdcs from papers. 

*Impact of speed*

Walking speed has a variable impact on the data. Generally, hip joint position error and hip angle error was not affected by speed. While joint position error in the ML axis was consistent across speed, ankle and toe joint center error increased with speed (i.e. Approximate RTMPose RMSE range from slowest to fastest speed, ankle: 9-16mm, toe:10-23mm) across the AP axis, and knee and ankle joint center increased across the ML axis (ie.e. Approximate RTMPose range from slowest to fastest speed: knee: 11-17, toe: 7-17mm), while the ankle error remained relatively consistent. Saggital knee and ankle angles also increased with speed (i.e. approximate RTMPose error from slowest to fastest speed, knee: 2.2-3.6°, ankle:1.6-3.2°). Joint angle error could be a result of the propogating positional error in trajectories. 

Speed had an asymmetric impact on spatiotemporal gait parameters. When spatial gait metrics were stratified by speed, LoA across all trackers widened with faster movement (i.e. approximate ViTPose LoA from slowest to fastest speed: ±19mm to ±88mm). Step length agreement decreased substantially with speed as opposed to stride length, which showed only a slight decrease. Temporal gait metric LoA were generally not impacted by speed, remaining relatively stable across all speeds, although for both stance and swing duration, agreement with the reference decreased substantially across speed.  

[something about why this is important]

*Impact of tracker*

Tracker behavior often showed systematic (or systemic?) differences. 

We found that ViTPose-derived 3D data was consistently overscaled compared to the reference marker-based data by about 2-3%. However, this scaling was invariate. Substantially higher joint trajectory was noted in the vertical axis as opposed to the AP or ML axes. As a result, our spatial parameters, which were both calculated in the direction of walking (AP axis), were largely unaffected by the scaling. ViTPose generally demonstrated the smallest bias and difference from the reference in gait metrics. However, care would need to be taken with calculating gait parameters that may depend on different axes (such as minimum toe clearance, which is the vertical height between the foot and the floor at the lowest point of swing) as we might expect the scaling to impact ViTPose accuracy to the reference (and real-world) distances measured. ViTPose generally had the lowest error in tracking hip and knee angles. While ankle angles were still under 7°, ViTPose-derived angles overshoot peak plantarflexion and SPM shows suprathreshold clusters across nearly the entire gait cycle, with a near consistent offset observed in gait cycle-normalized joint angles. This offset may be due to the vertical axis in the toe, as a consistent positional error could cause consistent angle error. 

MediaPipe-derived 3D data was generally accurate in joint trajectories and joint kinematics. However, SPM analysis of hip and knee angles shows consistent speed dependent error - with suprathreshold clusters surrounding peak hip extension and peak knee flexion that decrease across walking speed. Notably, these errors are not at the peaks themselves, but before and following them. MediaPipe also shows a consistent underestimation of peak plantarflexion. With spatiotemporal parameters, MediaPipie generally showed the widest LoA, although agreement was generally comparatble to other trackers at all speeds. Speed-dependant changes in MediaPipe could be a result of the one-euro filter @casiez1FilterSimple2012, an adaptive-low pass filter that lowers the cutoff frequency at lower speeds, reducing jitter at the expense of lag, while increasing the cutoff frequency at higher speeds to reduce lag. The larger errors at slower walking speeds, particularly in large flexion/extension movements, could be an artifact of the lag produce by the one euro filter adapting to changes in velocity from a slower movement. 

RTMPose was generally consistent across scaling, joint kinematics, and spatiotemporal parameters, while also showing the most accurate tracking of ankle kinematics.

Thus, RTMPose may be the best option for gait analysis. ViTPose may be an alternative option where scaling is not a concern. MediaPipe, with not requiring a GPU to use, remains a widely accessible option for all user, but with some systematic error to be aware of in its usage for gait analysis. 