== Discussion

*Joint center and joint kinematic accuracy*

Reconstructed joint center error was generally under 30 mm across all joints. The hip joint center exhibited the largest error, with RMSE values of ~20mm in the anterior-posterior and vertical axes across speed. Kinematic error was typically below 5°, with larger error observed only for the ViTPose-derived ankle angle at higher speeds. 

These metrics fall within ranges reported in prior markerless validation work. Joint errors of \~6-30mm have been reported across various systems ( @ripicComparisonThreedimensionalKinematics2023, @nakanoEvaluation3DMarkerless2020) and sagittal angle errors of 2-11° ( @kankoAssessmentSpatiotemporalGait2021, @uhlrichOpenCapHumanMovement2023). The hip is consistently identified as a challenging joint to estimatem with Kanko et al. reporting 3D Euclidean hip position error of 36 mm and a hip flexion/extension error of 11° @kankoConcurrentAssessmentGait2021, while Needham et al. noted systematic differences in hip and knee position tracking (~30-50mm) @needhamAccuracySeveralPose2021. Our kinematic errors fall between the 2-5° range that McGinley et al. suggest is suitable for clinical work @mcginleyReliabilityThreedimensionalKinematic2009.
 
SPM testing shows consistent suprathreshold clusters in early stance phase in knee and ankle kinematics across all speeds. These clusters are positioned consistently with the loading response phase of gait, where the knee undergoes transient flexion as a method of shock absorption and the ankle plantarflexes slightly in the first rocker phase. Thus, it is possible that these motions may be difficult for pose estimation software to track correctly. Additionally, heel strike and the resulting absorption of impact has been shown to cause skin surface movement that propogates throughout the lower limb @painSoftTissueMotion2002, and marker-based motion capture can be particularly sucsceptible to soft tissue artifacts during the landing phases of movement (@KinematicDifferencesOptical2013). As such, this a reminder that while our markerless system comparisons are in reference to a gold-standard method, it is not necessarily representative of true joint centers and their resulting kinematics, but rather the most accurate and available method we have to reconstruct them. 

*Gait parameter accuracy*

Generally, gait parameters show minimal bias and excellent agreement with the reference. Limits of agreement (LoA) for stride and step length, pooled across walking speeds, were within approximately ±70 mm across all pose estimation backends. Temporal agreement was similarly strong, with stance and swing duration LoA within ±40 ms for RTMPose and ViTPose and within ±70 ms for MediaPipe. Agreement was lowest for swing phase (ICC ≈ 0.90).

These findings are consistent with prior work. Kanko et al. reported similar LoA ranges (±70 mm for stride/step length and ±40-70 ms for temporal parameters), along with reduced agreement during swing phase @kankoAssessmentSpatiotemporalGait2021. This reduced agreement likely reflects higher velocities of the foot during swing, which may be more difficult to capture accurately at lower sampling rates. Additionally, at 30Hz temporal resolution is limited to ~33 ms increments which could obscure finer differences in timing. Higher framerate systems may provide more detailed information on temporal agreement while also improving sensitive metrics such as swing duration.  

Clinically, we can compare bland-altman to minimal detectable change values to assess whether our markerless setup would have the resolution to dscriminate between impaired and healthy populations. add some notes about some mdcs from papers. 

*Impact of speed*

Metrics based on spatial position (joint position/angle error, stride length, step length) demonstrated clear sensitivity to speed, while temporal metrics (heel strike and toe off timing error, stance duration, swing duration) appeared largely unaffected. However, temporal metrics should be interpreted within the context of measurement resolution. Our temporal measurements were limited by the framerate of the cameras and discretized to \~33 ms increments, which may obscure more subtle speed-dependant changes. 

Increased walking speed resulted in larger errors in joint position and angle, particularly in the anterior-posterior and vertical directions for distal joints. In contrast, hip position and angle error remained stable across all axes and speeds. Increased walking speed in gait primarily manifest in the AP and vertical axes, rather than ML motion, and our findings are consistent with this. Faster segment velocities likely amplify frame-to-frame tracking error, particularly for distal segments, contributing to reduced agreement. 

However, the specific axis affect different by joint as well. AP error increased most clearly at the ankle and toe, while vertical error increased more at the knee and toe, suggesting that the impact of speed is not global but differs from segment to segment. Spatial gait metrics (step and stride length), were largely more affected by speed then temporal metrics (swing and stance duration). 


[something about why this is important]

*Impact of tracker*

RTMPose-derived reconstructions were generally consistent across spatial, kinematic, and spatiotemporal gait metrics, without the speed-dependent temporal effects observed in MediaPipe or the spatial bias observed in ViTPose-derived reconstructions. Ankle kinematics were tracked with the lowest error among the evaluated methods. This suggests a balance between spatial accuracy and temporal stability relative to other evaluated approaches. 

MediaPipe SPM analyses revealed regions of significant difference flanking peak hip extension and knee flexion that decreased with increasing walking speed. These speed-dependent changes may be related to the behavior of the one-euro filter @casiez1FilterSimple2012 utilized in MediaPipe landmark smoothing. The one-euro filter is an adaptive low-pass filter that adjusts its cutoff frequency based on signal velocity - applying stronger smoothing during slower motion and less smoothing during faster motion, balancing lag and jitter. The regions surrounding peak angle excursions correspond to phases of rapid change in joint velocity, where the filter must adapt to changing signal dynamics. Transitions between low and high velocity phases may introduce temporal lag. At slower walking speeds, overall signal velocities are lower, potentially leading to increased smoothing and greater lag. As walking speed increases, reduced smoothing may allow the signal to more closely track rapid changes, resulting in smaller deviations.  

ViTPose-derived 3D reconstructions required a scaling factor of \~0.98 to align with the reference, suggesting an apparent 2-3\% size difference. Trajectory error was disproportionately elevated in the vertical direction compared to other tracker-derived data, suggesting that this discrepancy may be primarily vertical in nature. This is consistent with the minimal impact of the size difference observed on stride and step length, which are calculated along the AP direction. While ViTPose-derived knee and hip angles showed the lowest error overall, ankle angle error was notably higher. Given the sensitivity of foot segment orientation to small positional errors,  vertical positioning error at the toe may produce the near-constant plantarflexion offset and persistent suprathreshold SPM clusters observed across the gait cycle. Although ViTPose-derived estimates were generally accurate, care would need to be taken in calculating and assessing parameters that may depend on different axes (such as minimum toe clearance, which is the vertical height between the foot and the floor at lowest point of swing).

ViTPose differs from RTMPose and MediaPipe in that it is built on a vision transformer backbone, while RTMPose and MediaPipe are CNN-based. Both types of models handle spatial relationships differently. CNN-based models build connections between pixels over many layers, with spatial structure encoded into the architecture, while vision transformer models lack these inductive biases and must more heavily rely on learning spatial relationships from the data itself through self-attention layers @takahashiComparisonVisionTransformers2024, @LearningSpatialDecay. This reliance on learned spatial relationships could potentially contribute to the observed spatial offset, although testing of alternative vision transformer pose estimation software and additional testing in different environments with different hardware would be necessary before making this claim. 

These findings show that while all trackers preserved key patterns of movement, there are inherent characteristics of different pose estimation algorithms based on their specific architecture or implementation that may affect the reconstructed 3D data. This reinforces the need for an accessible method to compare pose estimation algorithms used for markerless motion capture under different conditions and for standard benchmarking methods. Thus, RTMPose may be the best option for gait analysis. ViTPose may be an alternative option where scaling is not a concern. MediaPipe, with not requiring a GPU to use, remains a widely accessible option for all user, but with some systematic error to be aware of in its usage for gait analysis
