
Walking is one of the most human behaviors, yet gait reflects a complex integration of systems (e.g., vision, neuromuscular, vestibular, and skeletal, to name a few). It is a highly coordinated and optimized process, governed by principles that shape its stability and efficiency, and disruptions to this efficiency can manifest as pathological gait @kuoDynamicPrinciplesGait2010. As such, gait can be a highly informative window into health, changing in recognizable patterns (e.g., cautious, stiff-legged or freezing patterns)  in response to disease and functional decline @osobaBalanceGaitElderly2019. For example, gait speed at midlife has been linked to cognitive function and decline @rasmussenAssociationNeurocognitivePhysical2019, characteristics of gait dysfunction could potentially be used to differentiate between different types of dementia @vergheseQuantitativeGaitDysfunction2007, and early gait abnormality can be used to help diagnose PD @galnaProgressionGaitDysfunction2015 and predicted decline in attention and memory @morrisGaitRatherCognition2017.

Accessible methods of quantifying gait enable its use as a non-invasive, early biomarker for diagnosis, disease characterization, and recovery and rehabilitation efficacy evaluation @scheetsUseMovementSystem2007. Marker-based motion capture remains the gold-standard for capturing accurate kinematic data, but is generally unsuitable for clinical use (see Chapter 1: Introduction I). Markerless motion capture offers an accessible approach for obtaining such measurements outside of specialized laboratory environments. However, existing systems may be limited be cost, hardware requirements or methodological constraints (see Chapter 2: Introduction II). 

The Free Motion Capture Project (FreeMoCap) @queenFreeMoCapFreeOpen2024 is a free, open-source motion capture system that reconstructs 3D kinematic data from synchronized videos using consumer-grade webcams (the software and its pipeline are described in detail in Chapter 3: FreeMoCap). By relying on low-cost hardware and open-source software, FreeMoCap lowers barriers to adoption in both clinical and research settings. Its modular architecture also enables integration and comparison of multiple pose estimation backends within the same reconstruction pipeline, enabling detailed benchmarking of tracking algorithm performance and accuracy. 

In the following chapter, we report the accuracy of several metrics (i.e., joint position, joint kinematics, gait event timing error, and spatiotemporal gait parameters) of the system over progressively faster walking speeds. Furthermore, we characterize the behavior of reconstructed 3D data from three different pose estimation software backends, MediaPipe @lugaresiMediaPipeFrameworkBuilding2019, RTMPose @jiangRTMPoseRealTimeMultiPerson2023, and ViTPose @xuViTPoseSimpleVision2022 and examine how the choice of pose estimation algorithms can shape downstream biomechanical measurements. 




