== Introduction

Walking is a deceptively simple behavior, yet biomechanically, it reflects a complex integration of systems (vision, neuromuscular, vestibular, and skeletal, to name a few). It is a highly coordinated and optimized process, governed by principles that shape its stability and efficiency, and disruptions to this efficiency can manifest as pathological gait @kuoDynamicPrinciplesGait2010. As such, gait can be a highly informative window into health, changing recognizably in response to disease and functional decline (e.g., cautious, stiff-legged or freezing patterns) @osobaBalanceGaitElderly2019. For example, gait speed at midlife has been linked to cognitive function and decline @rasmussenAssociationNeurocognitivePhysical2019, characteristics of gait dysfunction can differentiate between different types of dementia @vergheseQuantitativeGaitDysfunction2007, and early gait abnormalities have been used to help diagnose PD @galnaProgressionGaitDysfunction2015 and predict decline in attention and memory @morrisGaitRatherCognition2017.

Accessible methods of quantifying gait enable its use as a non-invasive, early biomarker for diagnosis, disease characterization, and recovery and rehabilitation efficacy evaluation @scheetsUseMovementSystem2007 @simonQuantificationHumanMotion2004. Marker-based motion capture remains the gold-standard for capturing accurate kinematic data, but is generally unsuitable for widespread clinical use (see Chapter 1). Markerless motion capture offers an accessible approach for obtaining such measurements outside of specialized laboratory environments. However, existing systems may be limited by cost, hardware requirements or methodological constraints (see Chapter 2). 

The Free Motion Capture Project (FreeMoCap) @queenFreeMoCapFreeOpen2024 is a free, open-source motion capture system that reconstructs 3D kinematic data from synchronized videos using consumer-grade webcams (see Chapter 3). By relying on low-cost hardware and open-source software, FreeMoCap lowers barriers to adoption in both clinical and research settings. Its modular architecture also enables integration and comparison of multiple pose estimation backends within the same reconstruction pipeline, enabling detailed benchmarking of tracking algorithm performance and accuracy. 

The following chapter examines the accuracy of a six-camera markerless motion capture system for capturing joint kinematics and spatiotemporal gait parameters over progressively faster walking speeds. Furthermore, it characterizes the behavior in reconstructed 3D data across three different pose estimation software backends, MediaPipe @lugaresiMediaPipeFrameworkBuilding2019, RTMPose @jiangRTMPoseRealTimeMultiPerson2023, and ViTPose @xuViTPoseSimpleVision2022, and examines how the choice of pose estimation algorithms can shape downstream biomechanical measurements. 




