= Conclusion
This work examined the development and use of a low-cost, markerless motion capture system using the FreeMoCap software, with the goal of evaluating its ability to meet three core design requirements: biomechanical utility, extensibility, and accessibility.

== Addressing biomechanical utility
_Requirement: The system should produce measurements whose agreement with reference data is in line with prior markerless validation studies, while capturing biomechanically meaningful patterns across tasks._

Biomechanical utility was evaluated across two validation tasks: treadmill gait and clinical balance assessment (CTSIB-M). In gait analysis, a six-camera FreeMoCap setup produced joint position and joint angle errors within the ranges reported by prior markerless validation studies, while also yielding spatiotemporal gait parameters in close agreement with the reference system. In the balance task, the same system demonstrated sensitivity to condition-dependent changes in commonly used posturographic metrics, including center of mass path length, sway area, and center of mass velocity, while maintaining agreement with the reference system.

At the same time, this work revealed that the utility of a markerless system cannot be summarized by any single accuracy metric. Within a single task, variations in execution (i.e., walking speed in gait analysis) affected the resulting data in ways that differed across joints, axes, and pose estimation backends. Different pose estimation backends exhibited distinct characteristics that substantially influenced downstream metrics: ViTPose introduced systematic scaling bias affecting joint position and angle error, while MediaPipe's One-Euro filter produced speed-dependent smoothing artifacts that were visible in SPM analysis, but proved advantageous for preserving small postural adjustments. Capture conditions examined in Chapter 8 (e.g., lighting, camera number, and camera placement) further examined how data quality is not a fixed property of the software but also function of the full capture setup and environment.

Critically, several of these characteristics (in particular, the effect of MediaPipe's temporal smoothing) only became apparent when examining pose estimation behavior across both tasks. These cross-task patterns would not have emerged from either validation study alone, underscoring that characterizing a pose estimation backend requires evaluation across a range of movement types. 

Building a trustworthy evidence base for any markerless system therefore requires open, repeated validation across tasks, populations, and recording conditions.

== Addressing extensibility
_Requirement: The system should support multiple pose estimation backends and permit task or population-specific modifications when out-of-the-box markerless pipelines are insufficient._

Extensibility, in this context, refers not only to software modularity, but to the ability to preserve a usable motion capture workflow when standard pose estimation assumptions no longer hold. The modular FreeMoCap architecture described in Chapter 4 was designed to allow pose estimation backends to be integrated and exchanged without requiring changes to the rest of the processing pipeline. Chapters 5 and 6 demonstrate this through the integration of three backends—MediaPipe, RTMPose, and ViTPose—within the same system, enabling direct comparison of their reconstruction characteristics under identical recording conditions.

Chapter 7 tested the limits of this extensibility. Standard pose estimation models, trained predominantly on able-bodied populations, failed to reliably track a transfemoral prosthesis user whose limb morphology fell outside their training distribution. By integrating DeepLabCut into the FreeMoCap architecture and training a custom model for this population, the study showed that the system could be adapted when out-of-the-box backends were insufficient. This serves as a proof of concept that extensibility is not limited to swapping among existing general-purpose backends, but includes the ability to incorporate task or population-specific models when standard approaches fail. More broadly, this architecture provides a framework for integrating future pose estimation methods that may be more inclusive to certain populations as they emerge. 

== Addressing accessibility
_Requirement: The system should reduce financial, computational, and methodological barriers to motion capture by supporting low-cost hardware, minimizing specialized software and hardware requirements, and providing openly available, reusable analysis workflows._

Chapter 4 describes the design choices made to reduce barriers to adoption. The system runs on low-cost cameras (all data in this work were collected using six \$20 webcams) and the default use of MediaPipe as a pose estimation backend allows the software to run without a GPU. Users retain the option to use higher-end equipment as resources allow, but the baseline cost of entry remains low.

While accessibility is difficult to fully quantify, several indicators suggest broad practical reach. Optional telemetry pings collected from September 2022 through February 2026 indicate that FreeMoCap has been used by at least 10,000 users across approximately 140 countries, with roughly 53% of observed users returning to use the software more than once. The project’s open-source community also shows substantial engagement, with approximately 7,400 GitHub stars and 617 forks. In addition, a community Discord server, which as of April 2026 had approximately 3,000 members, provides channels for help requests and weekly community chats. User questions on this forum span a wide range of applications, from animation to scientific validation and experimental setup.

A further dimension of accessibility, particularly for scientific use, is the fully open-source nature of the analysis pipeline. All comparison and analysis code used in this work, including FreeMoCap-Qualisys synchronization, gait analysis methods, and balance-specific posturography metrics, is publicly available. This serves a dual purpose: promoting transparency and reproducibility for researchers adopting the system, while also providing reusable tools for benchmarking pose estimation backends across new tasks and populations, thereby supporting continued evaluation of biomechanical utility and extensibility.

== Overall limitations

The findings of this work should be interpreted within several key limitations that reflect both the underlying structure of markerless motion capture systems and the specific design choices of this study. First, data in this work were primarily collected at a sampling rate of 30 Hz. While sufficient for many kinematic analyses, this temporal resolution limits the detection of fine timing differences and may obscure small trends or errors in temporal metrics. More broadly, the performance of markerless motion capture remains strongly dependent on the underlying pose estimation algorithm. Errors in 2D keypoint detection—arising from factors such as occlusion, visual ambiguity, or model limitations—propagate directly into 3D reconstruction and downstream biomechanical measures. As such, if a pose estimation model is unable to reliably track a given movement or population, it becomes unsuitable for motion capture within this framework. Although approaches such as custom-trained DeepLabCut models can address some of these limitations, they introduce additional requirements in the form of time-intensive data labeling and model training. Additionally, the results presented in this work are task and population-specific. Validation was conducted using gait on a treadmill, a static balance assessment, and a prosthesis user. While these domains were selected to represent a range of movement complexities, the findings may not generalize to other populations, environments, or movement types (such as overground gait or more dynamic balance tasks).

Finally, markerless motion capture systems remain sensitive to experimental conditions, including camera configuration and visibility. Occlusion and limited viewpoints can reduce reconstruction accuracy, reinforcing the importance of multi-camera setups and careful data collection protocols.
  
== Future directions

The most immediate future direction is continued development of the FreeMoCap software. Many of the potential benefits described in this work (modular pose estimation, open-source benchmarking, adaptability through custom model integration) require continued iteration to make these components easily accessible to researchers across domains and experience levels. This includes packaging the gait and balance analyses developed here into a toolbox that other researchers can freely use, extend and improve. 

More broadly, I believe the field would benefit from shared, standardized validation datasets that allow direct comparison across markerless systems and pose estimation backends. FreeMoCap, as a free and open-source platform, is well-positioned to support that effort.

== Significance

This work contributes to a growing effort to study and measure human movement outside of the traditional laboratory environment. Across research and clinical fields, there are many groups that would benefit from non-invasive measurement tools capable of returning data with a level of depth approaching that of marker-based motion capture. By emphasizing accessibility, modularity, and open-source development, the FreeMoCap software aims to provide a practical and adaptable tool for use beyond the lab. While marker-based motion capture remains the gold standard for precise movement measurement, the work presented here is not intended as a replacement for such systems, but rather as an expansion of where and how movement can be measured, and who is able to measure it.
