== Current use

FreeMoCap has seen adoption across a range of biomechanical applications. This includes independent rsearch, including studies of reaching and grasping kinematics @mazroueiCatchingSmallBalls2026 and saggital-plane gait mechanics under controlled postural manipulations @nunez-lisboaUnderstandingGaitAlterations2024. Validation work has also shown favorable agreement against marker-based system for spatiotemporal gait parameters @dariciLowCostMarkerlessMotion2025a, squat and countermovement jump mechanics @minogueValidationFreetoUseMarkerless2025, and with regards to clinical application for functional gait assessment as well @dariciLowCostMarkerlessMotion2025a. Beyond biomechanics, the software has been adopted for multimodal corpus construction in computational linguistics @peechattMULTICOLLABMultimodalCorpus2024 @orrMULTICOLLABASLAffectiveComputing2024 @nunnariDGSFabeln1MultiAngleParallel2024.

FreeMoCap has been used in a number of research studies already.

A recent study by Mazrouei et al. utilized FreeMoCap when examining kinematics of reaching and grasping in the hand @mazroueiCatchingSmallBalls2026. Núñez-Lisboa et al. found that they were able to use FreeMoCap to detect changes in sagittal-joint mechanics from controlled postural manipulations @nunez-lisboaUnderstandingGaitAlterations2024. Darici et al. found a 3 camera FreeMoCap system could accurately capture spatiotemporal gait parameters and further found that FreeMoCap could be suitable for use in Functional Gait Analysis @dariciLowCostMarkerlessMotion2025a. Minogue et al. found high correlation and low RMSE in measuring squat movement and countermovement jumps against a marker-based system @minogueValidationFreetoUseMarkerless2025. The software has also been mentioned in a series of corpus-building papers in the computational linguistics field @peechattMULTICOLLABMultimodalCorpus2024 @orrMULTICOLLABASLAffectiveComputing2024 @nunnariDGSFabeln1MultiAngleParallel2024.  

FreeMoCap has found community outside of the academic field as well. It has drawn a growing community of independent animators, small game studies, and motion capture enthusiasts - users for whome traditional motion capture and commerical markerless motion capture has been out of reach. This breadth of adoption, from clinical validation to creative production, speaks to both the acessibility of the system and the need for low-cost, accessible motion capture tools. 

