== Handling Motion Capture Data

As discussed earlier, a key direction of FreeMoCap is becoming a flexible framework that can integrate multiple pose estimation algorithms. However, each pose estimation algorithm outputs its own set of keypoints, with different names, numbers of keypoints and ordering. Without a standardized representation, biomechanical analyses would require writing separate downstream analysis code for each tracker, making it difficult to compare results or extend the system. 

To this end, we developed a skeletal representation framework (`SkellyModels`) that decouples tracker-specific data from downstream analyses. Each supported tracker is described by a structured configuration file (YAML) that specifies keypoint names and relevant anatomical information (such as segment connections and anthropometric data for center of mass calculations). The analyses pipelines used in this work read from this configuration rather than being written for any particular tracker. In practice, this means that adding a new pose estimation tracker to the analysis pipeline requires authoring only a new configuration file. This could be a user-friendly way to encourage contributions to the software. The three-tracker comparisons presented in Chapters 3 and 4 were conducted using a single shared analysis pipeline enabled by this architecture, and the framework was also key in integrating a custom-trained DeepLabCut model for prosthetic limb tracking (see Chapter 6).


tends to output its own specific keypoints. This means that this data must be handled in such a way so as to not require writing different downstream analysis code for each different tracker. 

To this end, we developed a skeletal modeling framework (`SkellyModels`), which is a layered-data model where tracker-specific knowledge is isolated in structured configuration (YAML) files. Each file specifies keypoint identities and relevant anatomical information (such as segment connections and anthropometric data for center of mass calculations). Without a standardized representation, biomechanical would require writing separate downstream analysis code for each tracker, making it difficult to compare results or extend the system. To this end, we developed a skeletal representation framework 




In the process of collecting, processing, and analyzing motion capture data from a variety of sources, it became clear that there was a need for an efficient method to gracefully handle a myriad of outputs from our 3D reconstruction software. For the most of our pipeline, we consider the data to be a 3D point cloud and generally separated from what it is tracking. However, once we start applying constraints and calculated analyses, we can no longer handle the data agnostic of its shape and source. For examples, in throughout the main studies in the following chapter we examine 3D data reconstructed from different pose estimation software backends. While mainly, each human pose estimation software generally tracks the same joint centers, there are slight differences between the points returned by each. In Chapter4 specifically, we introduce the idea of training completely custom models based on user-need. Accordingly, that means our pipeline needs to be ready to handle any 3D data following any kind of tracking.  

This led to the development of `skellymodels`, a respository for loading, manipulating, and saving out 3D motion capture data from any source. User-written YAMLs are used to create definitions of the specific input models to the pipeline. This includes at minimum the keypoint names detected by the pose estimation algorithm, while optionally allowing for definitions of segments that can be used in data visualization and provide a basis for further optional analyses such as center-of-mass calculations or applying rigid body constraints. Starting with a user-written document lays the groundwork for a future where we can integrate completely custom-trained models into our pipeline with minimal effort on the user side. Additionally, this also allows for a more defined path for outside users to contribute new pose estimation software to our pipeline. 

A key part of `skellymodels` is that it is also made to make the manipulation of motion capture for biomechanical analyses more convenient. The models provide easy ways to load in FreeMoCap `npy` and `csv` files. Biomechanical analyses such as center-of-mass and rigid body calculations are linked to the model. Making it easy to add more or other things. jh