== Pose Estimation

Pose estimation is a computer vision task that identifies meaningful keypoints within an image. In human pose estimation, these keypoints typically correspond to joint centers. Pose estimation is a critical part of modern markerless motion capture software. In practice, pose estimation produces 2D keypoint locations in pixel coordinates for each camera and each frame of a recording. Nakano et al. describe a markerless motion capture system based on OpenPose @nakanoEvaluation3DMarkerless2020, while Theia Markerless uses a proprietary custom-trained algorithm. 

The base FreeMoCap pipeline utilizes MediaPipe @lugaresiMediaPipeFrameworkBuilding2019, a free-open source framework based on the CNN BlazePose @bazarevskyBlazePoseOndeviceRealtime2020. While from a research perspective, several admittedly more accurate pose estimation options are available, we made this choice from a practicality and usability standpoint. MediaPipe is simple to install and interface with using Python scripts. It is incredibly lightweight and can be run on a CPU-only computer. From a user accessibility standpoint, MediaPipe makes our software accessible to the widest range of users. 

Although pose estimation plays a critical role in markerless motion capture, general out-of-the-box models are often not well suited for movement science applications @seethapathiMovementScienceNeeds2019, @needhamAccuracySeveralPose2021. In the past few years, work has been made to address some of these issues by creating datasets and algorithms that are task and population specific @yeungAthletePose3DBenchmarkDataset2025 @yingLDPoseInclusiveHumana @RefiningOpenPoseNew. However, the challenge of integrating them and using them in a markerless motion capture software remains. Most existing motion capture systems are tightly coupled to a single pose estimation backend, forcing researchers who wish to use alternative models to build custom pipelines from scratch.

To ensure FreeMoCap could scale with evolving research needs, we developed `skellytracker`, a modular sub-package that decouples pose estimation from the rest of the processing pipeline. We define a standardized interface for pose estimation models using a modular design pattern. New trackers can be integrated by implementing this interface, allowing them to be used interchangeably within the same pipeline without modifying downstream processing steps.

This has multiple benefits. Similar to how users can scale hardware to match their research needs, we also aim for users to be able to 'plug in' different pose estimation software according to their research needs. This could allow for the use of pose estimation algorithms trained on more specific datasets for specific research needs. If successful, this plug-in model leverages the open-source nature of the framework to enable community-driven contributions. Researchers can integrate pose estimation models tailored to specific populations or tasks, making them immediately accessible to others. Ultimately, this approach could accelerate the translation of novel pose estimation methods from research settings into practical use.

The following work will present alongside MediaPipe, three different pose estimation trackers, ViTPose, RTMPose, and a custom-trained DeepLabCut model, as an evaluation of the benefits of a modular, pose estimation-agnostic framework for markerless motion capture.
