
== Discussion

The aim of this work was to determine whether a markerless motion capture system is sensitive to small postural balance changes using center of mass (COM) metrics and accurate in postural measurement when compared to a marker-based reference. We evaluated three pose estimation backends from which 3D data were reconstructed. 


Our results show that MediaPipe-derived data preserved condition-dependent ordering in COM path length across progressively more difficult conditions and demonstrated strong agreement with the reference system. MediaPipe-derived data also showed strong sensitivity to the effects of visual, proprioceptive, and combined visual/proprioceptive perturbations on balance. In contrast, both RTMPose- and ViTPose-derived data exhibited poorer agreement with the reference system and reduced sensitivity to changes in balance across conditions. 

Because vertical center-of-mass motion during quiet standing is minimal, position variability in the vertical direction can serve as an estimate of measurement noise. Vertical COM variability for both RTMPose- and ViTPose-derived data was substantially higher than that of the reference and MediaPipe-derived data, suggesting increased measurement noise that may contribute to their reduced sensitivity and agreement.

The strong sensitivity and agreement exhibited by MediaPipe by be due to its One-Euro filter. As previously discussed (Chapter 3 Discussion), MediaPipe uses the One-Euro filter for temporal smoothing @casiez1FilterSimple2012, which adaptively adjusts cutoff frequency based on signal velocity, applying stronger smoothing when velocity is low. In contrast, RTMPose and ViTPose-derived data may be more susceptible to frame-to-frame landmark noise, which could obscure small postural changes of interest, particularly in conditions where movement amplitudes are minimal. Future work could evaluate the implementation of similar temporal filtering to these backends' 2D keypoints prior to 3D reconstruction in order to improve their suitability for balance assessments. These findings suggest that temporal stability in landmark tracking may be critical for detecting subtle balance changes.  

Mean velocity between systems showed close agreement, with both systems capturing progressive increases in velocity over more difficult conditions. In posturography, sway velocity is regarded as one of the most reliable and clinically sensitive parameters @paillardTechniquesMethodsTesting2015 @jancovavseteckovaWHATROLEBODY2013. Of note however, is that in posturography measures of body sway and path length are typically calculated from center of pressure (COP). This work uses COM as a means to calculate these metrics, which should be taken into consideration. While COM and COP are biomechnically coupled @winterBiomechanicsMotorControl2009 (i.e., COP moves to constrain the movement of COM in balance), a study by XXXX found that COP detected changes in eyes closed balance that COM could not @panzerBiomechanicalAssessmentQuiet1995. As such, future work could compare COM changes to COP from a force plate as a reference. 

Although gait and dynamic movements is often validated for markerless motion capture, none so far have validated the Romberg graded test conditions (or any of its variants). However, the use of COM to measure path length has been validated in other systems. Ferrari et al. found that an IMU could discriminate between eyes open and closed conditions on solid ground, with moderate to strong agreement with a force plate @ferrariConstructValidityWearable2024. Gonzalez et al., notably, found that the Kinect V2 sensitivity was too low to discriminate between this conditions in quiet standing @gonzalezComparisonBodySway2021. In contrast, the present study found that COM path length using MediaPipe could sufficiently distinguish all four standing conditions, suggesting that modern markerless systems may offer sufficient resolution to detect condition-dependent changes in COM sway that earlier markerless devices could not.

Clinically, the NIH Toolbox uses an uses an implementation of the CTSIB-M called the Standing Balance Test, which uses a smartphone accelerometer worn as a waist to detect postural sway, calculating path length metrics from that @StandingBalanceTest, which has also been validated in use for balance studies @pellerValidityReliabilityNIH2023, demonstrating clinical need and use case for this data. Accelerometer data can be difficult to extract meaningful signals from CITE, and this study shows how detailed kinematic data can be used to obtain this data. 
