
In comparison to gait, balance presents a fundamentally different measurement challenge. As opposed to capturing repeated kinematic cycles, balance assessment requires resolving much more suble postural adjustments. These adjustments result from the continuous coordination of visual, vestibular, and neuromuscular systems @horakClinicalAssessmentBalance1997. 

Assessments of balance can be useful for diagnosis (e.g., early detection of fall risk in individuals @manciniRelevanceClinicalBalance2010) or in rehabilitation (e.g, tailoring treatment strategies to the individual @visserClinicalUtilityPosturography2008. Clinical assessments of balance tend to be limited to practical, easily useable methods. The Berg Balance Scale, for example, assesses dynamic balance and consists of 15 tasks, each graded on a 5 point scale consiting of factors such as external supervision or time to task completion @bergMeasuringBalanceElderly1989. One such assessment is the Modified Clinical Test of Sensory Interaction on Balance (CTSIB-M)@ModifiedClinicalTest2013. In this test, participants maintain balance under four conditions that systematically vary visual input and surface stability (eyes open/closed; firm/foam surface). These manipulations provide a graded increase in task difficulty, allowing for controlled assessment of postural stability across conditions.

However, pure qualitative methods may not be enough to fully grasp the complex motor skills that underlie balance @paillardTechniquesMethodsTesting2015 @visserClinicalUtilityPosturography2008. Visual analysis may also be subjective and suffer from tester bias @manciniRelevanceClinicalBalance2010. Quantitative analysis could provide valuable into patient balance, noting subtle trends that visual assessment may miss, and providing quantitative metrics of individual trends in balance over time, whether it be in aging or injury recovery. 

Marker-based motion capture is the "gold-reference" for providing detailed, accurate kinematic data. However, implementation of these systems for widespread clinical use is infeasible due to cost, required expertise, and extensive preparation and burden on the participant (See Chapter 1: Introduction I). 

Markerless motion capture systems present accessible, non-invasive ways to collect data about patient balance. Eveleigh et al. @eveleighPrincipalComponentAnalysis2023 and Federolf et al. @federolfValidationMarkerlessTheia3D2025 both validate Theia Markerless for balance and postural assessment using principal component analysis (PCA) to extract whole-body movement patterns. However, few markerless motion capture studies have examined static balance using CoM metrics. Chaumeil et al. previously demonstrated 1 cm agreement of COM estimates from Theia Markerless with a marker-based reference during dynamic balance tasks @chaumeilAgreementMarkerlessMarkerbased2024, while Needham et al. ...

To the author's knowledge, no multi-camera markerless motion capture system has been validated for use in the CTSIM-M. Here, we use the FreeMoCap system, a free, open-source motion capture system to measure postural metrics in participants completing the CTSIB-M. Many markerless systems are often validated on dynamic movements. This contributions of this work are three-fold: first, where the previous chapter assessed the ability of the FreeMoCap system to accurately measure dynamic movements, this chapter examines the sensitivity of the system to subtle changes in posture across progressively difficult conditions in a participant, and the accuracy of those changes relative to a marker-based reference; second, this work examines the ability of markerless motion capture to be used for the CTSIB-M test, which has yet to be evaluation for this kind of system; third, this work characterizes the performance of three different pose estimation backends, MediaPipe, RTMPose and ViTPose for balance assessment. 
