
In comparison to gait, balance presents a fundamentally different measurement challenge. As opposed to capturing repeated kinematic cycles, balance assessment requires resolving more subtle postural adjustments. These adjustments result from the continuous coordination of visual, vestibular, and neuromuscular systems @horakClinicalAssessmentBalance1997. 

Assessments of balance can be useful for diagnosis (e.g., early detection of fall risk in individuals @manciniRelevanceClinicalBalance2010) or in rehabilitation (e.g, tailoring treatment strategies to the individual @visserClinicalUtilityPosturography2008). Clinical assessments of balance tend to be limited to practical, easily useable methods @manciniRelevanceClinicalBalance2010 @bergMeasuringBalanceElderly1989 @tinettiPerformanceOrientedAssessmentMobility1986. The Modified Clinical Test of Sensory Interaction on Balance (CTSIB-M) @ModifiedClinicalTest2013, for example, only requires a foam balance pad and a stopwatch. In this test, participants maintain balance under four conditions that systematically vary visual input and surface stability (eyes open/closed; firm/foam surface). Test scores are based on how long the participant is able to maintain each condition.

Although qualitative methods such as these can be reliable, alone they may not be enough to fully grasp the complex motor skills that underlie balance @paillardTechniquesMethodsTesting2015 @visserClinicalUtilityPosturography2008, while also suffering from tester bias @manciniRelevanceClinicalBalance2010. Quantitative analysis could provide valuable insight into patient balance, noting subtle trends that visual assessment may miss, and providing quantitative metrics of individual trends in balance over time, whether during aging or injury recovery.

Marker-based motion capture is the "gold-reference" for providing detailed, accurate kinematic data. However, implementation of these systems for widespread clinical use is infeasible due to cost, required expertise, and extensive preparation and burden on the participant (See Chapter 1: Introduction I). 

Markerless motion capture systems present accessible, non-invasive ways to collect data about patient balance. Eveleigh et al. @eveleighPrincipalComponentAnalysis2023 and Federolf et al. @federolfValidationMarkerlessTheia3D2025 both validate Theia Markerless for balance and postural assessment using principal component analysis (PCA) to extract whole-body movement patterns. However, few markerless motion capture studies have examined static balance using CoM metrics. Chaumeil et al. previously demonstrated 1 cm agreement of COM estimates from Theia Markerless with a marker-based reference during dynamic balance tasks @chaumeilAgreementMarkerlessMarkerbased2024.

To my knowledge, no multi-camera markerless motion capture system has been validated for use in the CTSIB-M. Here, we use the FreeMoCap system, a free, open-source motion capture system to measure postural metrics in participants completing the CTSIB-M. The contributions of this work are three-fold: first, this chapter examines the accuracy and sensitivity of the system to subtle postural changes across progressively difficult conditions in comparison to a marker-based reference; second, this work examines the ability of markerless motion capture to be used for the CTSIB-M test, which has yet to be evaluated for this kind of system; third, this work characterizes the performance of three different pose estimation backends, MediaPipe, RTMPose and ViTPose for balance assessment. 
