#import "elife.typ": *

= Discussion

In this study, we characterize a FreeMoCap motion-capture setup using six, low-cost webcams across two movement tasks: gait and balance. We found the three 2D pose estimation backends, MediaPipe, RTMPose, and ViTPose, used in this study produced distinct error profiles, and their relative performance different across our movement tasks. Critically, the distinct behavioral differences show that validity of a markerless motion capture system is better understood in relation to a specific pipeline configuration and measurement context than as a fixed property of the system as a whole.


== Agreement across gait
Joint trajectory errors were generally under 30 mm and sagittal joint angle errors below 5°, consistent with ranges reported across other markerless validation studies (6-30 mm for trajectories, 2-11° for sagittal angles) @ripicComparisonThreedimensionalKinematics2023 @nakanoEvaluation3DMarkerless2020 @kankoAssessmentSpatiotemporalGait2021 @uhlrichOpenCapHumanMovement2023. These errors also fall within the 2-5° range that McGinley et al. characterize as potentially acceptable for many clinical interpretations, although suitability ultimately depends on the outcome and application @mcginleyReliabilityThreedimensionalKinematic2009.

Spatiotemporal gait parameters pooled across walking speeds showed minimal bias and strong agreement with the reference. Agreement was lowest for swing duration, although it remained strong (ICC ≈ 0.90), consistent with the reduced swing-phase agreement reported by Kanko et al. @kankoAssessmentSpatiotemporalGait2021. A limitation of the present gait analysis is the 30 Hz camera sampling rate, which was intentionally retained to characterize performance using low-cost hardware. At this frame rate, gait event timing is resolved in approximately 33 ms increments, so a one frame difference represents a comparatively large proportion of the shorter swing phase. This limits sensitivity to small timing differences and may partly explain the lower agreement observed for swing duration. Future validation with higher framerate cameras could help distinguish pose-estimation error from temporal sampling limitations.


== Agreement and sensitivity across balance

MediaPipe-derived COM path length preserved the progressive increase across conditions observed in the marker-based reference with strong agreement (ICC = 0.985). MediaPipe-derived data also showed strong sensitivity to the effects of visual, proprioceptive, and combined visual/proprioceptive perturbations on balance, capturing condition-dependent changes in COM path length with near one-to-one agreement to the reference. Mean horizontal velocity was comparable between MediaPipe-derived data and the reference across all conditions, a notable finding given that sway velocity is regarded as one of the most reliable and clinically sensitive posturographic parameters @paillardTechniquesMethodsTesting2015 @jancovavseteckovaWHATROLEBODY2013.

// To our knowledge, no markerless motion capture study has validated the CTSIB-M. However, COM path length has been evaluated using other technologies, with mixed results: an IMU distinguished eyes-open from eyes-closed standing with moderate-to-strong agreement with force-plate measures @ferrariConstructValidityWearable2024, whereas Kinect V2 lacked sufficient sensitivity to discriminate between the same conditions @gonzalezComparisonBodySway2021.

The present analysis characterizes balance using center of mass behavior, whereas conventional posturography more commonly relies on center of pressure (COP). Although COM and COP are biomechanically coupled @winterBiomechanicsMotorControl2009 (i.e., COP moves to constrain the movement of COM in balance), they are not interchangeable measures. Panzer et al., for example, reported changes in eyes-closed balance that were detectable in COP but not COM @panzerBiomechanicalAssessmentQuiet1995. Future work should therefore compare markerless COM estimates directly with force-plate COP and determine whether full-body kinematics provide complementary information beyond conventional posturographic measures.

// Importantly, these gait and balance analyses were obtained using six consumer webcams costing approximately \$20 each. The ability to recover meaningful gait measurements and detect subtle condition-dependent changes in postural sway using such low-cost hardware supports the potential for motion capture to become substantially more accessible to researchers, clinicians, educators, and other users who may not have access to specialized laboratory systems. Understanding how the components of these systems shape the resulting measurements will be essential to realizing that potential. We therefore next consider how the choice and implementation of pose estimation backends influenced the reconstructed 3D data and downstream biomechanical outcomes.


== Pose estimation backends produce distinct downstream error profiles

We found that each pose estimation backend produced distinct spatial and temporal characteristics that meaningfully affected the reconstructed 3D data and the biomechanical outcomes derived from it.

MediaPipe-derived COM trajectories were sufficiently stable to distinguish the small condition-dependent changes in postural sway that were not consistently recovered using RTMPose or ViTPose, both of which produced greater COM path length and velocity. However, the 95% ellipse area was similar across all three backends, suggesting that the overall spatial extent of sway was reasonably preserved even when path-dependent measures differed. One likely contributor to MediaPipe's stronger performance on path length and velocity is its internal temporal landmark smoothing, which uses an implementation of the One-Euro filter @casiez1FilterSimple2012. Because this filter applies stronger smoothing during slower movement and less during faster movement, it may suppress frame-to-frame jitter during quiet standing while preserving responsiveness during larger movements. Consistent with this interpretation, MediaPipe-derived hip and knee angles also showed speed-dependent differences during gait, with suprathreshold SPM clusters around peak excursions decreasing as walking speed increased. However, because filtered and unfiltered MediaPipe outputs were not directly compared, the contribution of temporal smoothing remains an interpretation rather than a demonstrated mechanism.

ViTPose-derived reconstructions showed a different spatial error profile. A median scaling factor of 0.98 (range: 0.96-0.98) was required for alignment with the marker-based reference, while trajectory error was disproportionately elevated in the vertical direction, suggesting that the discrepancy was not explained by uniform scaling alone. ViTPose-derived ankle angles also showed a persistent plantarflexed offset and suprathreshold SPM clusters across much of the gait cycle. Because foot-segment orientation is particularly sensitive to ankle and toe landmark position, vertical landmark-positioning error may have contributed to this pattern. Hip and knee kinematics and anteroposterior gait measures were nevertheless generally accurate, indicating that ViTPose errors were outcome dependent rather than uniformly distributed across the reconstruction.


RTMPose-derived reconstructions were comparatively consistent across spatial, kinematic, and spatiotemporal gait outcomes and produced the lowest ankle-angle errors among the evaluated backends. In contrast, RTMPose-derived COM trajectories did not consistently distinguish among the balance conditions, illustrating that strong performance during large-amplitude gait movements does not necessarily imply sufficient temporal stability for resolving subtle postural displacements.


Differences between pose estimators are often attributed primarily to their training datasets, but the present findings suggest that architectural and implementation-level choices may also shape downstream measurements in important ways. MediaPipe’s stronger balance performance, for example, may reflect its use of adaptive temporal smoothing rather than an inherent advantage of the underlying pose estimator itself. If so, other backends such as RTMPose or ViTPose may also support sensitive balance measurements when paired with appropriate temporal filtering. More broadly, pose-estimation methods should be characterized not only by overall accuracy, but by the spatial and temporal properties they introduce into reconstructed trajectories and by how those properties interact with the outcome being measured. These implementation details should therefore be documented explicitly in validation studies and treated as potentially modifiable components of the analysis pipeline.

== Markerless motion capture validity depends on movement context

Markerless motion capture performance varied across movements with different spatial and temporal demands, and performance in one context did not necessarily predict performance in another. Meaningful variation was evident even within gait: as walking speed increased, joint-position and joint angle errors generally increased, particularly in the anteroposterior and vertical directions at distal joints. These effects were not uniform across joints, axes, outcomes, or pose estimation backends, indicating that movement speed interacted with specific characteristics of the measurement pipeline rather than simply increasing error globally. The range of walking speeds examined here was therefore useful not only for evaluating gait across realistic conditions, but also for revealing error patterns that may have remained hidden in a single-speed validation.

More broadly, performance established under one version of a task should not be assumed to generalize across the full range of conditions in which that task may be performed. Markerless motion-capture systems may behave differently as movement speed, amplitude, complexity, viewpoint, or environmental conditions change. Validation is therefore most informative when it contributes to a profile of system performance across representative conditions rather than reducing the system to a single estimate of accuracy.

== Building richer profiles of markerless motion-capture performance

The present findings suggest that markerless motion-capture benchmarking should focus on characterizing the spatial and temporal behavior of specific implementations in relation to the movement and outcome of interest. Rather than asking which pose estimation algorithm is most accurate overall, researchers may benefit more from knowing which algorithms are most suitable for the specific movments and conditions they are interesting in exploring.

Developing these performance profiles requires validation methods that are themselves transparent and reusable. If markerless motion-capture systems are expected to operate across laboratories, clinics, community settings, and other real-world environments, their behavior will need to be characterized under variation in factors such as camera quality, frame rate, lighting, camera number and configuration, participant characteristics, and movement type. To support this process, we have released the validation pipeline used to generate the analyses reported here so that the same procedures can be reproduced, modified, and extended. We plan to expand this work toward a broader set of benchmarking tools for systematically characterizing pose-estimation and reconstruction behavior across tasks and acquisition conditions.

This approach may be especially important as markerless motion capture continues to become more compositional. The ability to exchange pose estimation backends means that an algorithm need not be treated as a fixed property of a motion capture system. Instead, pose estimators can be selected according to the movement, population, or outcome of interest and evaluated within a common acquisition and reconstruction framework. FreeMoCap is being developed to support this model by providing standardized interfaces through which alternative pose estimation methods can be integrated, configured, evaluated, and made available to other users.

== Practical use and broader application of FreeMoCap

FreeMoCap has already been applied across a range of research and applied contexts, including gait and other biomechanical analyses, reaching and grasping @mazroueiCatchingSmallBalls2026, computational linguistics @orrMULTICOLLABASLAffectiveComputing2024 @peechattMULTICOLLABMultimodalCorpus2024 @nunnariDGSFabeln1MultiAngleParallel2024, animation @landaEvaluatingIdleAnimation2025, and robotic or assistive-device development @obukhovHybridVerificationMethod2026. This breadth reflects one advantage of retaining access to reconstructed three-dimensional landmark trajectories rather than constraining the system to a single downstream biomechanical model or analysis. 

A limitation of the present study is that data were collected under controlled laboratory conditions that were favorable for markerless reconstruction. The recording space was well lit and relatively uncluttered, camera placement was unconstrained, and sufficient room was available to deploy all six cameras around the participant. These conditions likely reduced challenges associated with occlusion, poor illumination, restricted viewpoints, and limited camera placement that may be encountered in clinical, community, or home environments. The present results therefore establish performance under an intentionally low-cost hardware configuration, but not under the full range of environmental constraints that may accompany real-world deployment.

More generally, accessibility does not remove practical measurement constraints. Consumer cameras introduce limits in frame rate, image quality, synchronization, field of view, and sensitivity to environmental conditions, while markerless reconstruction remains dependent on appropriate camera placement, calibration, visibility, and the quality of the pose-estimation output. Practical guidance for acquisition, calibration, camera configuration, and interpretation of reconstructed data is therefore an important complement to quantitative validation. We provide additional discussion of these considerations in [Appendix/Supplementary Note X].

Taken together, the present results support viewing FreeMoCap not only as a low-cost motion-capture system, but as an open framework for progressively characterizing how markerless measurement behaves across algorithms, tasks, and acquisition conditions. The goal is not to identify a single configuration that is universally optimal, but to make the behavior and limitations of different configurations sufficiently visible that users can select and evaluate methods appropriate to their particular application.


= Conclusion

A low-cost, six-camera FreeMoCap system produced meaningful gait measurements across three pose estimation backends and, when using MediaPipe, detected small condition-dependent changes in postural sway. However, performance varied across backends, outcomes, tasks, and walking speeds. These results show that markerless motion capture validity is conditional on the complete measurement configuration and the movement context in which it is evaluated, rather than being a fixed property of a software platform or pose estimation model. Validation and benchmarking should therefore characterize the spatial and temporal behavior of specific implementations across representative movement conditions and clearly report the boundaries within which acceptable performance has been demonstrated.
