#import "elife.typ": *

= Discussion

This study demonstrates that an accessible, six-camera markerless motion capture system can produce meaningful gait and balance measurements, while also showing that performance varies substantially across pose-estimation backends, movement conditions, and outcome measures.

== Agreement and sensitivity across gait and balance

Across the evaluated backends, the system produced gait measurements that generally agreed well with the marker-based reference, while MediaPipe-derived data also captured small condition-dependent changes in postural sway.

=== Gait
Joint trajectory errors were generally under 30 mm and sagittal joint angle errors below 5°, consistent with ranges reported across other markerless validation studies (6-30 mm for trajectories, 2-11° for sagittal angles) @ripicComparisonThreedimensionalKinematics2023 @nakanoEvaluation3DMarkerless2020 @kankoAssessmentSpatiotemporalGait2021 @uhlrichOpenCapHumanMovement2023. These errors also fall within the 2–5° range that McGinley et al. characterize as acceptable or potentially acceptable for many clinical interpretations, although suitability ultimately depends on the outcome and application @mcginleyReliabilityThreedimensionalKinematic2009.

Spatiotemporal gait parameters pooled across walking speeds showed minimal bias and strong agreement with the reference. Agreement was lowest for swing duration, although it remained strong (ICC ≈ 0.90), consistent with the reduced swing-phase agreement reported by Kanko et al. @kankoAssessmentSpatiotemporalGait2021. At the 30 Hz sampling rate used here, gait-event timing was resolved in approximately 33 ms increments. A one-frame difference therefore represents a comparatively large proportion of the shorter swing phase, limiting the resolution with which small timing differences can be detected. Higher-frame-rate cameras may improve the temporal accuracy of these measures.


=== Balance

MediaPipe-derived COM path length preserved the progressive increase across conditions observed in the marker-based reference, with strong agreement between systems (ICC = 0.985). MediaPipe-derived data also showed strong sensitivity to the effects of visual, proprioceptive, and combined visual/proprioceptive perturbations on balance, capturing condition-dependent changes in COM path length with near one-to-one agreement to the reference. Mean horizontal velocity was comparable between systems across all conditions, a notable finding given that sway velocity is regarded as one of the most reliable and clinically sensitive posturographic parameters @paillardTechniquesMethodsTesting2015 @jancovavseteckovaWHATROLEBODY2013.

To our knowledge, no markerless motion capture studies to date have validated the CTSIB-M. However the use of COM to measure path length has been validated in other systems. Ferrari et al. found that an IMU could discriminate between eyes open and closed conditions on solid ground, with moderate to strong agreement with a force plate @ferrariConstructValidityWearable2024. Gonzalez et al., notably, found that the Kinect V2 sensitivity was too low to discriminate between these conditions in quiet standing @gonzalezComparisonBodySway2021. 

Taken together, these findings suggest that the validity of a markerless motion capture system is difficult to reduce to a single metric of accuracy. Accuracy did not transfer uniformly across pose-estimation backends or movement conditions: each pose estimator produced a distinct downstream error profile, and performance changed both between gait and balance and across walking speeds within gait. Validity should therefore be understood as a property of the each of the components within the markerless motion capture pipeline (e.g., camera hardware, pose estimation backend, post-processing) and the specific movement conditions and outcome measures of interest.

== Pose-estimation backends produce distinct downstream error profiles

We found that each pose estimation backend produced distinct spatial and temporal characteristics that meaningfully affected the reconstructed 3D data and the biomechanical outcomes derived from it.

MediaPipe-derived COM trajectories were sufficiently stable to distinguish the small condition-dependent changes in postural sway that were not consistently recovered using RTMPose or ViTPose. Although 95% ellipse areas were broadly comparable across backends, RTMPose and ViTPose-derived data showed substantially greater COM path length and velocity. This suggests that the overall spatial extent of sway was reasonably preserved, while frame-to-frame landmark variability inflated measures that depend on the temporal trajectory through that space. Because true COM displacement during quiet standing was small, this variability constituted a large proportion of the measured signal and obscured differences among balance conditions.

MediaPipe’s stronger balance performance is likely related to its internal temporal landmark smoothing, which uses an implementation of the One-Euro filter @casiez1FilterSimple2012. The One-Euro filter adaptively adjusts its cutoff frequency according to signal velocity, applying stronger smoothing during slower movement to suppress jitter and less smoothing during faster movement to preserve responsiveness. This behavior may have reduced the frame-to-frame variability that affected RTMPose- and ViTPose-derived balance measures. However, the same smoothing behavior may also alter the dynamics of faster movements. During gait, MediaPipe-derived hip and knee angles showed suprathreshold SPM clusters around peak excursions, with cluster magnitude and duration decreasing as walking speed increased. The location and speed dependence of these differences are consistent with adaptive smoothing: stronger smoothing at lower movement velocities may introduce lag around periods of changing angular velocity, whereas reduced smoothing at higher velocities may allow rapid transitions to be followed more closely.


ViTPose-derived reconstructions exhibited a different error profile. They required a median scaling factor of 0.98 (range: 0.96-0.98) to align with the marker-based reference, indicating an apparent size difference of approximately 2-4%. rajectory error was disproportionately elevated in the vertical direction, suggesting that the discrepancy was anisotropic rather than a uniform difference in scale. This spatial error may also have propagated into joint-angle estimates: ViTPose-derived ankle angles showed a consistent plantarflexion offset and persistent suprathreshold SPM clusters across the gait cycle. Because foot-segment orientation is sensitive to small errors in toe and ankle position, vertical landmark-positioning error may have contributed to this pattern. Although ViTPose-derived hip and knee kinematics and anteroposterior gait parameters were generally accurate, outcomes that depend strongly on vertical positioning, such as minimum toe clearance, should therefore be interpreted cautiously.


RTMPose-derived reconstructions were comparatively consistent across spatial, kinematic, and spatiotemporal gait outcomes. They did not exhibit the same speed-dependent temporal pattern observed in MediaPipe-derived gait data or the apparent spatial bias observed with ViTPose, and RTMPose produced the lowest ankle-kinematic errors among the evaluated backends. Nevertheless, RTMPose-derived COM trajectories were not sufficiently temporally stable to consistently distinguish among the balance conditions, illustrating that strong performance for relatively large gait movements did not ensure sensitivity to small postural displacements.

Future work implementing a similar temporal smoothing filter for RTMPose, ViTPose, or other pose estimation software may allow them to be used for similar balance related tasks. During gait, however, the same smoothing strategy was associated with systematic differences around periods of rapidly changing joint motion, and these differences varied with walking speed. The contrasting effects of temporal stability across gait and balance also illustrate why markerless performance cannot be characterized independently of the movement being measured. 

These findings demonstrate that pose-estimation backends are not interchangeable inputs to an otherwise fixed reconstruction pipeline. Their downstream behavior depends not only on the underlying model, but also on implementation details such as temporal smoothing, which may be enabled or disabled through a single runtime setting. Such details should therefore be documented explicitly in validation studies, because seemingly minor configuration choices can meaningfully alter the resulting 3D data.

More broadly, pose-estimation methods should be characterized in terms of the specific spatial and temporal behaviors they introduce, rather than reduced to a simple ranking of overall accuracy. MediaPipe's One-Euro filter, for example, appeared beneficial for detecting small-amplitude postural sway by suppressing frame-to-frame variability, while also being associated with speed-dependent differences during gait. This suggests that the apparent accuracy of a pose-estimation backend may depend partly on the dynamics of the movement being measured. Applying comparable temporal smoothing to RTMPose or ViTPose may improve their suitability for balance outcomes, but its effects would need to be evaluated across both slow and rapid movements. These backend-specific tradeoffs therefore motivate a broader consideration of how task and movement condition shape markerless motion-capture validity.


