#import "elife.typ": *

= Discussion

This study demonstrates that an accessible, six-camera markerless motion capture system built from consumer webcams costing approximately \$20 each can produce meaningful gait and balance measurements, while also showing that validity cannot be reduced to a single metric of accuracy. Accuracy did not transfer uniformly across pose estimation backends or movement conditions: each pose estimator produced a distinct downstream error profile, and performance changed both between gait and balance and across walking speeds within gait. Validity should therefore be understood as a property of each component of the markerless motion capture pipeline (e.g., camera hardware, pose estimation backend, post-processing) together with the specific movement conditions and outcome measures of interest.


== Agreement and sensitivity across gait and balance

Across the evaluated backends, the markerless system, from all pose estimation backends, produced gait measurements that generally agreed well with the marker-based reference, while MediaPipe-derived data also captured small condition-dependent changes in postural sway.

=== Gait
Joint trajectory errors were generally under 30 mm and sagittal joint angle errors below 5°, consistent with ranges reported across other markerless validation studies (6-30 mm for trajectories, 2-11° for sagittal angles) @ripicComparisonThreedimensionalKinematics2023 @nakanoEvaluation3DMarkerless2020 @kankoAssessmentSpatiotemporalGait2021 @uhlrichOpenCapHumanMovement2023. These errors also fall within the 2-5° range that McGinley et al. characterize as acceptable or potentially acceptable for many clinical interpretations, although suitability ultimately depends on the outcome and application @mcginleyReliabilityThreedimensionalKinematic2009.

Spatiotemporal gait parameters pooled across walking speeds showed minimal bias and strong agreement with the reference. Agreement was lowest for swing duration, although it remained strong (ICC ≈ 0.90), consistent with the reduced swing-phase agreement reported by Kanko et al. @kankoAssessmentSpatiotemporalGait2021. At the 30 Hz sampling rate used here, gait-event timing was resolved in approximately 33 ms increments. A one-frame difference therefore represents a comparatively large proportion of the shorter swing phase, limiting the resolution with which small timing differences can be detected. Higher-frame-rate recordings may improve temporal outcome measures and help separate pose estimation error from sampling limitations.


=== Balance

MediaPipe-derived COM path length preserved the progressive increase across conditions observed in the marker-based reference, with strong agreement between systems (ICC = 0.985). MediaPipe-derived data also showed strong sensitivity to the effects of visual, proprioceptive, and combined visual/proprioceptive perturbations on balance, capturing condition-dependent changes in COM path length with near one-to-one agreement to the reference. Mean horizontal velocity was comparable between systems across all conditions, a notable finding given that sway velocity is regarded as one of the most reliable and clinically sensitive posturographic parameters @paillardTechniquesMethodsTesting2015 @jancovavseteckovaWHATROLEBODY2013.

To our knowledge, no markerless motion capture studies to date have validated the CTSIB-M. However the use of COM to measure path length has been validated in other systems. Ferrari et al. found that an IMU could discriminate between eyes open and closed conditions on solid ground, with moderate to strong agreement with a force plate @ferrariConstructValidityWearable2024. Gonzalez et al., notably, found that the Kinect V2 sensitivity was too low to discriminate between these conditions in quiet standing @gonzalezComparisonBodySway2021. 

while this work uses center of mass as a measure of balance, posturographic metrics often use center of pressure. While COM and COP are biomechanically coupled @winterBiomechanicsMotorControl2009 (i.e., COP moves to constrain the movement of COM in balance), Panzer et al. found that COP detected changes in eyes closed balance that COM could not @panzerBiomechanicalAssessmentQuiet1995. Future work should compare markerless COM measures directly with force-plate COP and determine whether full-body kinematics provide information beyond conventional posturographic outcomes.

Importantly, these results were obtained using six consumer webcams costing approximately \$20 each. The ability to recover meaningful gait measurements and detect subtle condition-dependent changes in postural sway using such low-cost hardware supports the potential for motion capture to become substantially more accessible to researchers, clinicians, educators, and other users who may not have access to specialized laboratory systems. Understanding how the components of these systems shape the resulting measurements will be essential to realizing that potential. We therefore next consider how the choice and implementation of pose estimation backends influenced the reconstructed 3D data and downstream biomechanical outcomes.


== Pose estimation backends produce distinct downstream error profiles

We found that each pose estimation backend produced distinct spatial and temporal characteristics that meaningfully affected the reconstructed 3D data and the biomechanical outcomes derived from it.

MediaPipe-derived COM trajectories were sufficiently stable to distinguish the small condition-dependent changes in postural sway that were not consistently recovered using RTMPose or ViTPose. Although 95% ellipse areas were broadly comparable across backends, RTMPose and ViTPose-derived data showed substantially greater COM path length and velocity. This suggests that the overall spatial extent of sway was reasonably preserved, while frame-to-frame landmark variability inflated measures that depend on the temporal trajectory through that space. Because true COM displacement during quiet standing was small, this variability constituted a large proportion of the measured signal and obscured differences among balance conditions.

MediaPipe's stronger balance performance is likely related to its internal temporal landmark smoothing, which uses an implementation of the One-Euro filter @casiez1FilterSimple2012. The One-Euro filter adaptively adjusts its cutoff frequency according to signal velocity, applying stronger smoothing during slower movement to suppress jitter and less smoothing during faster movement to preserve responsiveness. This behavior may have reduced the frame-to-frame variability that affected RTMPose- and ViTPose-derived balance measures. However, the same smoothing behavior may also alter the dynamics of faster movements. During gait, MediaPipe-derived hip and knee angles showed suprathreshold SPM clusters around peak excursions, with cluster magnitude and duration decreasing as walking speed increased. The location and speed dependence of these differences are consistent with adaptive smoothing: stronger smoothing at lower movement velocities may introduce lag around periods of changing angular velocity, whereas reduced smoothing at higher velocities may allow rapid transitions to be followed more closely.

ViTPose-derived reconstructions exhibited a different error profile. They required a median scaling factor of 0.98 (range: 0.96-0.98) to align with the marker-based reference, indicating an apparent size difference of approximately 2-4%. rajectory error was disproportionately elevated in the vertical direction, suggesting that the discrepancy was anisotropic rather than a uniform difference in scale. This spatial error may also have propagated into joint-angle estimates: ViTPose-derived ankle angles showed a consistent plantarflexion offset and persistent suprathreshold SPM clusters across the gait cycle. Because foot-segment orientation is sensitive to small errors in toe and ankle position, vertical landmark-positioning error may have contributed to this pattern. Although ViTPose-derived hip and knee kinematics and anteroposterior gait parameters were generally accurate, outcomes that depend strongly on vertical positioning, such as minimum toe clearance, should therefore be interpreted cautiously.

RTMPose-derived reconstructions were comparatively consistent across spatial, kinematic, and spatiotemporal gait outcomes. They did not exhibit the same speed-dependent temporal pattern observed in MediaPipe-derived gait data or the apparent spatial bias observed with ViTPose, and RTMPose produced the lowest ankle-kinematic errors among the evaluated backends. Nevertheless, RTMPose-derived COM trajectories were not sufficiently temporally stable to consistently distinguish among the balance conditions, illustrating that strong performance for relatively large gait movements did not ensure sensitivity to small postural displacements. Future work implementing a similar temporal smoothing filter for RTMPose, ViTPose, or other pose estimation software may allow them to be used for similar balance-related tasks, although its effects would need to be evaluated across both slow and rapid movements, since during gait the same smoothing strategy was associated with systematic differences around periods of rapidly changing joint motion that varied with walking speed.

Often, we attribute accuracy differences between pose estimators to the composition of their training datasets. While this is an important factor, the present findings also suggest that architectural and implementation-level differences can influence the reconstructed data in ways that are not often characterized. Such details should therefore be documented explicitly in validation studies, because seemingly minor configuration choices can meaningfully alter the resulting 3D data. More broadly, pose estimation methods should be characterized in terms of the specific spatial and temporal behaviors they introduce, rather than reduced to a simple ranking of overall accuracy. These backend-specific tradeoffs motivate a broader consideration of how task and movement condition shape markerless motion-capture validity.


== Markerless validity depends on movement context

Markerless motion capture performance varied across movements with different spatial and temporal demands, and performance in one movement context did not necessarily predict performance in another, as MediaPipe's temporal smoothing illustrates in improving sensitivity to subtle postural sway while being associated with speed-dependent differences during gait. Meaningful variation was also observed within gait alone: as walking speed increased, joint-position and joint-angle errors generally increased, particularly in the anteroposterior and vertical directions at distal joints. Critically, these effects were not uniform across joints, axes, outcomes, or backends, indicating that movement speed interacted with specific characteristics of the measurement pipeline rather than simply increasing error globally.

The range of walking speeds examined here was therefore important not only for evaluating gait across realistic conditions but for revealing error patterns that may not have been apparent in a single-speed validation. MediaPipe's speed-dependent SPM patterns are one example. More broadly, performance established under one version of a task should not be assumed to generalize across the full range of conditions in which that task is performed. Markerless motion capture benchmarks should therefore evaluate representative variations in movement speed, amplitude, and complexity and report the conditions under which acceptable performance has been demonstrated. Such benchmarking would provide more useful guidance than a single aggregate estimate of accuracy and would help define the range of applications for which a particular pose estimation and processing configuration is appropriate.

== Implications for markerless motion capture use and benchmarking

These findings have several implications for how markerless motion capture systems are evaluated and applied. First, pose estimation backends should be selected based on the movement and outcome of interest rather than on a single overall measure of accuracy. Researchers should therefore consider whether the spatial and temporal characteristics of a particular backend are appropriate for the biomechanical variables they intend to measure.

This also highlights the need for modular, tracker-agnostic frameworks that allow pose estimation backends and processing configurations to be interchanged while holding the remainder of the pipeline constant. Such frameworks would make it easier to characterize how specific pose estimation methods affect reconstructed 3D data and downstream biomechanical outcomes.

We aim to continue developing FreeMoCap as a platform that makes a broad range of computer vision methods accessible to biomechanics researchers through a common, reproducible workflow. By standardizing how pose estimation backends are integrated, configured, and evaluated, we intend to make it easier to compare algorithms directly, benchmark their behavior across tasks, and validate their downstream biomechanical outputs without requiring each research group to construct a new processing pipeline from scratch. In this way, FreeMoCap is being developed not only as an accessible motion capture system, but also as shared infrastructure for comparing and validating computer vision methods in biomechanical applications. 

= Conclusion

A low-cost, six-camera FreeMoCap system produced meaningful gait measurements across three pose estimation backends and, when using MediaPipe, detected small condition-dependent changes in postural sway. However, performance varied across backends, outcomes, tasks, and walking speeds. These results show that markerless motion capture validity is conditional on the complete measurement configuration and the movement context in which it is evaluated, rather than being a fixed property of a software platform or pose estimation model. Validation and benchmarking should therefore characterize the spatial and temporal behavior of specific implementations across representative movement conditions and clearly report the boundaries within which acceptable performance has been demonstrated.
