= Introduction

Although motion capture can provide detailed quantitative information relevant to biomechanics, clinical research, and a broad range of movement-science applications, deploying motion-capture tools beyond specialized laboratories remains difficult. Technologies introduced into clinical practice or real-world environments must balance measurement detail with accessibility, ease of use, and cost @kerrAdoptionStrokeRehabilitation2018 @buckleyRoleMovementAnalysis2019. Marker-based motion capture, for example, is widely treated as a reference standard for motion analysis and can be combined with force plates and electromyography to support detailed analyses of motor control, loading, and muscle activity @delpOpenSimOpensourceSoftware2007. However, its cost, specialized hardware, and requirement for technical expertise can limit translation into routine or distributed use @sinclairInfluenceTesterExperience2014 @camomillaHumanMovementAnalysis2017. A gap therefore remains between the detailed kinematics available in a motion-capture laboratory and the movement information that can be feasibly collected in clinical and real-world settings @weiMotionTrackingDaily2024.

*Markerless motion capture has evolved toward compositional pipelines*

Markerless motion capture (i.e., the extraction of kinematic data from video without physical markers) has developed in part as an attempt to close this gap. Early markerless approaches generally relied on tightly coupled combinations of image features, body models, and reconstruction procedures. Predefined body models were fit using information such as edges, silhouettes, and visual hulls @gavrila3DModelbasedTracking1996 @rosenhahnSystemMarkerlessMotion2006 @corazzaMarkerlessMotionCapture2006, such that the representation of the body was closely linked to the method used to recover it from images. In this sense, early markerless motion capture often functioned as a comparatively monolithic measurement method: changing how pose was represented or estimated could require substantial changes to the rest of the system.

The emergence of deep-learning-based pose estimation, beginning with methods such as DeepPose @toshevDeepPoseHumanPose2014 and OpenPose @caoOpenPoseRealtimeMultiPerson2019, marked a fundamental shift. Rather than relying on a complete hand-engineered procedure for fitting a body model to image features, learned models could infer anatomical landmark locations directly from images and provide a reusable intermediate representation. These methods have since become a dominant component of modern markerless motion capture @nagornyComprehensiveReviewRealTime2025. Combined with synchronized multiview recording and three-dimensional reconstruction, they helped transform markerless motion capture from a largely integrated method into a compositional measurement pipeline in which video acquisition, camera calibration, two-dimensional pose estimation, three-dimensional reconstruction, filtering, biomechanical modeling, and downstream analysis can increasingly be treated as separable stages.

*Compositional pipelines expand methodological choice and add complexity to validation*

This compositional structure has greatly expanded the design space of markerless motion capture. Modern systems can be assembled from different combinations of hardware, pose-estimation models, reconstruction approaches, and downstream analysis methods. Theia3D (Kingston, ON, Canada), for example, uses six or more hardware-synchronized cameras together with proprietary pose estimation and reconstruction methods and has demonstrated close agreement with marker-based reference systems for gait measures @kankoAssessmentSpatiotemporalGait2021. OpenCap @uhlrichOpenCapHumanMovement2023 uses synchronized iOS devices, supports multiple two-dimensional pose estimation models, triangulates detected landmarks across camera views, and subsequently uses a learned marker-augmentation model to infer anatomical marker locations for biomechanical modeling. Other reusable open-source systems, including Pose2Sim @pagnonPose2SimEndtoEndWorkflow2022 and PosePipe @cottonPosePipeOpenSourceHuman2022, as well as numerous laboratory-specific implementations @nakanoEvaluation3DMarkerless2020 @needhamDevelopmentEvaluationFully2022 @yangEvaluationCameraConfigurations2025, illustrate the diversity of ways in which these components can now be combined.

This flexibility has substantially lowered barriers to quantitative movement measurement from video, but it also complicates validation. Modern markerless motion capture is not a single measurement method with a single level of validity: choices made at different stages of the pipeline can influence the resulting data. Pose estimation algorithms, for example, reflect their training datasets, anatomical representations, and model architectures and can differ in performance across participants, poses, movements, viewpoints, and recording conditions @roggioComprehensiveAnalysisMachine2024 @needhamAccuracySeveralPose2021. Not all pose-estimation approaches are equally well suited to biomechanical applications @seethapathiMovementScienceNeeds2019, and similar dependencies can arise from camera configuration, reconstruction, filtering, and downstream modeling choices.

Validation of modern markerless motion capture therefore requires more than determining whether a system is simply “accurate.” Performance must also be characterized across pipeline configurations and measurement contexts, because a method that performs well for one task or biomechanical outcome may not perform equally well for another. Importantly, it remains unclear how these dependencies manifest under the low-cost acquisition conditions that make broader clinical and real-world deployment feasible, as many prior validation studies have relied on research-grade or purpose-built camera systems.

*FreeMoCap provides a low-cost framework for characterizing these choices*

FreeMoCap is a free and open-source markerless motion-capture framework designed around this compositional structure. It provides a common workflow for synchronized video acquisition, camera calibration, pose estimation, three-dimensional reconstruction, and post-processing using consumer-grade cameras without requiring a proprietary camera ecosystem. In the present study, the six-camera array was assembled using six consumer webcams for a total camera cost below \$150. Importantly for methodological characterization, FreeMoCap also allows components such as the pose estimation backend to be exchanged while the underlying recordings and much of the downstream reconstruction workflow are held constant. This makes it possible to examine how individual computational choices propagate into the resulting biomechanical measurements within a common acquisition framework.

Here, we characterize FreeMoCap against simultaneously recorded marker-based motion capture across two contrasting movement contexts: gait over a range of walking speeds and quiet-standing balance during the Modified Clinical Test of Sensory Interaction on Balance (CTSIB-M). These tasks impose substantially different measurement demands, ranging from large, dynamic, cyclic movement to subtle postural adjustments. We reconstruct each dataset using three pose-estimation backends (MediaPipe, RTMPose, and ViTPose) to determine how pose estimator choice affects downstream measurements within a common acquisition and reconstruction pipeline. We therefore ask whether an accessible webcam-based markerless motion-capture system can produce meaningful gait and balance measurements, and how measurement validity varies across pose-estimation backends, movement conditions, and biomechanical outcomes.
