= Introduction

Mundane actions can tell a story about human health. Even the act of rising from a chair involves a series of complex movements that shift the body's center of mass from a stable seated position into a less stable standing posture — smoothly, quickly, and without falling over @liKinematicAnalysisHuman2021 — and the time it takes to do so five times is itself a validated clinical assessment of functional health @FiveTimesSit2013. Many everyday movements embed similarly meaningful information. Gait is a highly coordinated, optimized process whose disruptions manifest recognizably as pathological patterns @kuoDynamicPrinciplesGait2010 @osobaBalanceGaitElderly2019. For example, gait characteristics can help differentiate types of dementia and support the early diagnosis of Parkinson's disease @vergheseQuantitativeGaitDysfunction2007 @galnaProgressionGaitDysfunction2015, and gait speed at midlife has been linked to cognitive function and decline (@rasmussenAssociationNeurocognitivePhysical2019). Balance, likewise, reflects the continuous coordination of visual, vestibular, and neuromuscular systems @horakClinicalAssessmentBalance1997, and its assessment supports the early detection of fall risk @manciniRelevanceClinicalBalance2010. Quantitative motion analysis is, then, the process of turning these everyday movements into measurements, extracting parameters that can be tracked, compared, and acted on.

We have developed comprehensive methods for quantifying human movement. Marker-based motion capture for example, the reference standard for accuracy measurement of 3D kinemaitcs, can be combined with tools such as force plates and electromyography to enable detailed analysis of motor control, loading, and muscle activity @delpOpenSimOpensourceSoftware2007. Deployment of this level of measurement in broader research, clinical and real-world contexts beyond specialized laboratories, however, remains difficult. Marker-based systems require costly infrastructure, dedicated recording spaces, trained personnel, and time-intensive participant preparation. Their measurements also depend on precise marker placement and are affected by soft-tissue artifact @sinclairInfluenceTesterExperience2014 @camomillaHumanMovementAnalysis2017. Together, these requirements limit where, how often, and by whom comprehensive motion analysis can be performed.

Clinical movement assessment has therefore evolved around methods that can be deployed quickly and reliably at the point of care, including observation and stopwatch-based functional tests. These assessments are valuable precisely because they are practical, but they provide less detailed information about how a movement was performed and may depend on clinician experience @sharmaFactorsInfluencingClinical2024 @nishiguchiReliabilityValidityGait2012. Technologies introduced into clinical practice must balance measurement detail with accessibility, ease of use, and cost @kerrAdoptionStrokeRehabilitation2018 @buckleyRoleMovementAnalysis2019. A gap consequently remains between the detailed kinematics available in a motion capture laboratory and the movement information that can be feasibly collected in clinical and real-world settings @weiMotionTrackingDaily2024.

Markerless motion capture—the extraction of kinematic data from video without physical markers—offers a route to detailed movement measurement outside specialized laboratories. Early systems inferred body position from image features such as edges, silhouettes, and visual hulls @gavrila3DModelbasedTracking1996 @rosenhahnSystemMarkerlessMotion2006 @corazzaMarkerlessMotionCapture2006, but these model-fitting approaches were computationally intensive and required considerable expertise to implement. The introduction of deep-learning pose estimation, beginning with methods such as DeepPose @toshevDeepPoseHumanPose2014 and OpenPose @caoOpenPoseRealtimeMultiPerson2019, marked a fundamental shift: rather than fitting predefined body models to image features, these methods learned to infer joint locations directly and have since become the dominant approach to markerless motion capture @nagornyComprehensiveReviewRealTime2025. Combined with synchronized multiview recording and 3D reconstruction, these advances have made it possible to build motion capture systems using readily available consumer cameras rather than specialized optical hardware.

Research-oriented multi-camera markerless motion capture has expanded rapidly. Commercial systems have demonstrated strong agreement with marker-based reference methods @kankoAssessmentSpatiotemporalGait2021, and a growing range of systems has been described in the research literature @nakanoEvaluation3DMarkerless2020 @needhamDevelopmentEvaluationFully2022 @yangEvaluationCameraConfigurations2025. Reusable open-source platforms such as OpenCap @uhlrichOpenCapHumanMovement2023, Pose2Sim @pagnonPose2SimEndtoEndWorkflow2022, and PosePipe @cottonPosePipeOpenSourceHuman2022 have further lowered the barrier to implementing markerless motion capture. Together, these developments have created an increasingly diverse ecosystem of tools for extracting biomechanical measurements from video.

Despite this rapid expansion, practical and methodological barriers to broader use remain. Existing systems vary in camera requirements, hardware cost, transparency, ease of use, and the extent to which individual processing components can be inspected, modified, or exchanged. Improvements in accessibility, usability, transparency, and adaptability are therefore not always achieved together. There remains a need for systems that combine inexpensive and widely available hardware with open, modular software while also providing clear evidence of the validity of the measurements they produce.

FreeMoCap was developed to address this need as a free, open-source markerless motion capture framework designed to operate with commodity webcams. In the present study, the six-camera array was assembled using consumer webcams costing approximately \$20 each, for a total camera cost of approximately \$120. FreeMoCap provides a common workflow for synchronized video acquisition, camera calibration, pose estimation, 3D reconstruction, and post-processing without requiring a proprietary camera ecosystem. Its modular architecture also allows individual processing components, including the pose-estimation backend, to be inspected, modified, or exchanged. Together, these features are intended to make detailed motion capture accessible and adaptable to a broad range of research and applied settings.

This flexibility is scientifically important because pose-estimation models are not interchangeable in their behavior. They differ in training data, landmark definitions, spatial localization, temporal stability, and processing strategies, and these differences may propagate into reconstructed 3D trajectories and downstream biomechanical outcomes. Performance can also vary across populations and movement contexts; models trained predominantly on able-bodied individuals, for example, may track people with altered limb morphology less reliably @zhouDiffusionModelsEnable2025 @cimorelliPortableInclinicVideobased2022. A modular framework therefore allows researchers both to select methods suited to a particular application and to evaluate how computational choices shape the resulting biomechanical data under otherwise consistent acquisition and reconstruction conditions.

Accessibility and adaptability are most useful when the validity of the resulting measurements is understood. Establishing validity requires comparison with an accepted reference and, because performance may depend on both the pose-estimation method and the movement being measured, evaluation across more than one computational configuration or task. Many validation studies evaluate a single pose-estimation method during a limited set of movements, making it difficult to determine how well reported performance generalizes across backends, outcomes, or movement conditions. It therefore remains unclear how an accessible markerless system performs across the range of movements for which it may be used and how strongly its validity depends on specific choices within the processing pipeline.

We addressed this gap by validating FreeMoCap against simultaneously recorded marker-based motion capture across two contrasting movement contexts: gait across a range of walking speeds and quiet-standing balance during the Modified Clinical Test of Sensory Interaction on Balance (CTSIB-M). These tasks impose substantially different spatial and temporal demands, ranging from large, dynamic, cyclic motion to subtle postural adjustments. Each task was reconstructed using three pose-estimation backends—MediaPipe, RTMPose, and ViTPose—to characterize how backend choice affected the resulting data within a common acquisition and reconstruction pipeline. We therefore aimed to determine whether an accessible webcam-based system could produce meaningful gait and balance measurements and how its validity varied across pose-estimation backends, movement conditions, and biomechanical outcomes.
