= Introduction

Motion capture provides detailed quantitative measurements of human movement, but deploying it beyond specialized laboratories remains difficult. Technologies introduced into clinical practice or real-world environments must balance measurement detail with accessibility, ease of use, and cost @kerrAdoptionStrokeRehabilitation2018 @buckleyRoleMovementAnalysis2019. For example, while marker-based motion capture (often considered a gold-standard in measurement analysis) can support detailed biomechanical analyses in a laboratory setting @delpOpenSimOpensourceSoftware2007, its cost, hardware, and technical expertise requirements can limit translation into widespread use @sinclairInfluenceTesterExperience2014 @camomillaHumanMovementAnalysis2017 . A gap therefore remains between the detailed kinematics available in a motion analysis laboratory and the movement information that can be feasibly collected in clinical and real-world settings @weiMotionTrackingDaily2024.

*Approaches to early and modern markerless motion capture*

Markerless motion capture (i.e., the extraction of kinematic data from video without physical markers) developed in part as an attempt to close this gap. In early markerless approaches, the representation of the body was often closely tied to the method used to recover its pose from images. Pre-defined or subject-specific body models were matched to image-derived information such as edges, silhouettes, or reconstructed visual hulls, with body pose estimated from the fitted model @gavrila3DModelbasedTracking1996 @rosenhahnSystemMarkerlessMotion2006 @corazzaMarkerlessMotionCapture2006. Substituting any one of these components could therefore require substantial changes to the rest of the system. 

The emergence of deep-learning-based pose estimation (e.g., DeepPose @toshevDeepPoseHumanPose2014 and OpenPose @caoOpenPoseRealtimeMultiPerson2019) marked a fundamental shift. Rather than fitting a body model to image features, pose estimation models could infer anatomical landmark locations directly from images. These methods have since become central to modern markerless motion capture @nagornyComprehensiveReviewRealTime2025, where two-dimensional keypoints estimated independently from multiple camera views can be triangulated to reconstruct three-dimensional movement.

*Compositional pipelines expand methodological choice and add complexity to validation*

Modern systems might now be better described as compositional pipelines, assembling different combinations of hardware, pose estimation models, reconstruction approaches, and downstream analysis methods. For example, Theia3D (Kingston, ON, Canada) uses six or more hardware-synchronized cameras together with proprietary pose estimation and reconstruction methods to collect 3D data @kankoAssessmentSpatiotemporalGait2021, while OpenCap, an open-source alternative, uses synchronized iOS devices, supports HRNet and OpenPose, and applies a learned marker-augmentation model after triangulation to infer anatomical marker locations for biomechanical modeling @uhlrichOpenCapHumanMovement2023. Reusable open-source platforms such as Pose2Sim @pagnonPose2SimEndtoEndWorkflow2022 and PosePipe @cottonPosePipeOpenSourceHuman2022, alongside numerous laboratory-specific implementations @nakanoEvaluation3DMarkerless2020 @needhamDevelopmentEvaluationFully2022 @yangEvaluationCameraConfigurations2025, further illustrate the range of possible configurations.

This flexibility, however, adds complexity to validation. Implementation and run-time choices at each stage of the pipeline can affect the resulting measurements. Pose estimation provides a clear example. Each algorithm can differ in performance across participants, poses, movements, and recording conditions, reflecting their training data and anatomical representations @needhamAccuracySeveralPose2021 @roggioComprehensiveAnalysisMachine2024, and not all are equally suited to biomechanical applications @seethapathiMovementScienceNeeds2019. Similar dependencies can arise from choices in camera configuration, reconstruction, filtering, and downstream modeling. Validation of markerless motion capture therefore benefits from characterizing how performance varies across methodological choices and measurement contexts, rather than treating accuracy as a fixed property of the system. This is especially important for low-cost systems intended for broader deployment, where performance may differ across tasks, movement intensities, biomechanical outcomes, and the acquisition conditions that make such accessibility possible.


*Characterizing an accessible, modular system across tasks and pose estimation backends*

Here we validate and characterize FreeMoCap, a free and open-source markerless motion-capture framework developed to make 3D kinematic measurement available without specialized hardware or programming expertise. FreeMoCap reconstructs 3D kinematics from synchronized video acquired with consumer-grade cameras through a graphical user interface and runs locally without requiring a cloud service or internet connection. Its major components, including synchronized acquisition, camera calibration, 2D pose estimation, 3D reconstruction, and post-processing, are independently maintained and separable, allowing individual stages to be modified or exchanged.

Prior studies have validated FreeMoCap under specific configurations and movement tasks. Darici et al. reported strong agreement for spatiotemporal gait measures @dariciLowcostMarkerlessMotion2026, while Minogue et al. found strong sagittal-plane agreement during squatting and countermovement jumping, with larger errors for some joint angles @minogueValidationFreetoUseMarkerless2025. Núñez-Lisboa et al. further showed that FreeMoCap could detect experimentally induced changes in gait mechanics @nunez-lisboaUnderstandingGaitAlterations2024. Each of these studies used MediaPipe for pose estimation and examined dynamic, large-amplitude movement, leaving open how performance depends on the pose estimation backend and how it behaves when the movement of interest is small.

In the present study, we characterize a six-webcam FreeMoCap system, assembled for a total camera cost below \$150, against simultaneously recorded marker-based motion capture during two tasks: gait over a range of walking speeds and standing balance during the Modified Clinical Test of Sensory Interaction on Balance (CTSIB-M). These tasks impose substantially different measurement demands, from large, dynamic, cyclic movement to subtle postural adjustments. Each dataset was reconstructed using three pose-estimation backends (MediaPipe, RTMPose, and ViTPose), with acquisition, calibration, and reconstruction held constant. We evaluate how measurement validity varies across pose estimation backends, movement conditions, and biomechanical outcomes, and whether an inexpensive webcam-based system can provide meaningful gait and balance measurements.

